module SummitPokeInfo
	@allspecies = [:VENUSAUR,:CHARIZARD,:BLASTOISE,:BUTTERFREE,:BEEDRILL,:PIDGEOT,:RATICATE,:RATICATE_ALOLA,:FEAROW,:ARBOK,:RAICHU,:RAICHU_ALOLA,:SANDSLASH,:SANDSLASH_ALOLA,:NIDOQUEEN,:NIDOKING,:CLEFABLE,:NINETALES,:NINETALES_ALOLA,:WIGGLYTUFF,:VILEPLUME,:PARASECT,:VENOMOTH,:DUGTRIO,:DUGTRIO_ALOLA,:PERSIAN,:PERSIAN_ALOLA,:GOLDUCK,:PRIMEAPE,:ARCANINE,:POLIWRATH,:ALAKAZAM,:MACHAMP,:VICTREEBEL,:TENTACRUEL,:GOLEM,:GOLEM_ALOLA,:RAPIDASH,:RAPIDASH_GALAR,:SLOWBRO,:SLOWBRO_GALAR,:DODRIO,:DEWGONG,:MUK,:MUK_ALOLA,:CLOYSTER,:GENGAR,:HYPNO,:KINGLER,:ELECTRODE,:EXEGGUTOR,:EXEGGUTOR_ALOLA,:MAROWAK,:MAROWAK_ALOLA,:HITMONLEE,:HITMONCHAN,:WEEZING,:WEEZING_GALAR,:KANGASKHAN,:SEAKING,:STARMIE,:MRMIME,:JYNX,:PINSIR,:TAUROS,:GYARADOS,:LAPRAS,:DITTO,:VAPOREON,:JOLTEON,:FLAREON,:OMASTAR,:KABUTOPS,:AERODACTYL,:SNORLAX,:DRAGONITE,:MEGANIUM,:TYPHLOSION,:FERALIGATR,:FURRET,:NOCTOWL,:LEDIAN,:ARIADOS,:CROBAT,:LANTURN,:XATU,:AMPHAROS,:BELLOSSOM,:AZUMARILL,:SUDOWOODO,:POLITOED,:JUMPLUFF,:SUNFLORA,:QUAGSIRE,:ESPEON,:UMBREON,:SLOWKING,:SLOWKING_GALAR,:WOBBUFFET,:GIRAFARIG,:FORRETRESS,:STEELIX,:GRANBULL,:SCIZOR,:SHUCKLE,:HERACROSS,:MAGCARGO,:URSARING,:OCTILLERY,:MANTINE,:SKARMORY,:HOUNDOOM,:KINGDRA,:DONPHAN,:HITMONTOP,:MILTANK,:BLISSEY,:TYRANITAR,:SCEPTILE,:BLAZIKEN,:SWAMPERT,:MIGHTYENA,:BEAUTIFLY,:DUSTOX,:LUDICOLO,:SHIFTRY,:SWELLOW,:PELIPPER,:GARDEVOIR,:MASQUERAIN,:BRELOOM,:SLAKING,:NINJASK,:SHEDINJA,:EXPLOUD,:HARIYAMA,:DELCATTY,:SABLEYE,:MAWILE,:AGGRON,:MEDICHAM,:MANECTRIC,:SWALOT,:SHARPEDO,:WAILORD,:CAMERUPT,:TORKOAL,:GRUMPIG,:FLYGON,:CACTURNE,:ALTARIA,:ZANGOOSE,:SEVIPER,:LUNATONE,:SOLROCK,:WHISCASH,:CRAWDAUNT,:CLAYDOL,:CRADILY,:ARMALDO,:MILOTIC,:BANETTE,:TROPIUS,:CHIMECHO,:ABSOL,:GLALIE,:WALREIN,:HUNTAIL,:GOREBYSS,:RELICANTH,:SALAMENCE,:METAGROSS,:TORTERRA,:INFERNAPE,:EMPOLEON,:STARAPTOR,:BIBAREL,:KRICKETUNE,:LUXRAY,:ROSERADE,:RAMPARDOS,:BASTIODON,:WORMADAM_PLANTCLOAK,:WORMADAM_SANDYCLOAK,:WORMADAM_TRASHCLOAK,:MOTHIM,:VESPIQUEN,:PACHIRISU,:FLOATZEL,:CHERRIM,:GASTRODON,:AMBIPOM,:DRIFBLIM,:LOPUNNY,:MISMAGIUS,:HONCHKROW,:PURUGLY,:SKUNTANK,:BRONZONG,:SPIRITOMB,:GARCHOMP,:LUCARIO,:HIPPOWDON,:DRAPION,:TOXICROAK,:CARNIVINE,:LUMINEON,:ABOMASNOW,:WEAVILE,:MAGNEZONE,:LICKILICKY,:RHYPERIOR,:TANGROWTH,:ELECTIVIRE,:MAGMORTAR,:TOGEKISS,:YANMEGA,:LEAFEON,:GLACEON,:GLISCOR,:MAMOSWINE,:PORYGONZ,:GALLADE,:PROBOPASS,:DUSKNOIR,:FROSLASS,:ROTOM,:ROTOM_HEAT,:ROTOM_WASH,:ROTOM_FROST,:ROTOM_FAN,:ROTOM_MOW,:SERPERIOR,:EMBOAR,:SAMUROTT,:WATCHOG,:STOUTLAND,:LIEPARD,:SIMISAGE,:SIMISEAR,:SIMIPOUR,:MUSHARNA,:UNFEZANT,:ZEBSTRIKA,:GIGALITH,:SWOOBAT,:EXCADRILL,:AUDINO,:CONKELDURR,:SEISMITOAD,:THROH,:SAWK,:LEAVANNY,:SCOLIPEDE,:WHIMSICOTT,:LILLIGANT,:KROOKODILE,:DARMANITAN,:DARMANITAN_GALAR,:MARACTUS,:CRUSTLE,:SCRAFTY,:SIGILYPH,:COFAGRIGUS,:CARRACOSTA,:ARCHEOPS,:GARBODOR,:ZOROARK,:CINCCINO,:GOTHITELLE,:REUNICLUS,:SWANNA,:VANILLUXE,:SAWSBUCK,:EMOLGA,:ESCAVALIER,:AMOONGUSS,:JELLICENT,:ALOMOMOLA,:GALVANTULA,:FERROTHORN,:KLINKLANG,:EELEKTROSS,:BEHEEYEM,:CHANDELURE,:HAXORUS,:BEARTIC,:CRYOGONAL,:ACCELGOR,:STUNFISK,:STUNFISK_GALAR,:MIENSHAO,:DRUDDIGON,:GOLURK,:BISHARP,:BOUFFALANT,:BRAVIARY,:MANDIBUZZ,:HEATMOR,:DURANT,:HYDREIGON,:VOLCARONA,:CHESNAUGHT,:DELPHOX,:GRENINJA,:DIGGERSBY,:TALONFLAME,:VIVILLON,:PYROAR,:FLORGES,:GOGOAT,:PANGORO,:FURFROU,:MEOWSTIC,:AEGISLASH,:AROMATISSE,:SLURPUFF,:MALAMAR,:BARBARACLE,:DRAGALGE,:CLAWITZER,:HELIOLISK,:TYRANTRUM,:AURORUS,:SYLVEON,:HAWLUCHA,:DEDENNE,:CARBINK,:GOODRA,:KLEFKI,:TREVENANT,:GOURGEIST,:AVALUGG,:NOIVERN,:DECIDUEYE,:INCINEROAR,:PRIMARINA,:TOUCANNON,:GUMSHOOS,:VIKAVOLT,:CRABOMINABLE,:RIBOMBEE,:WISHIWASHI,:LYCANROC_MIDDAY,:LYCANROC_MIDNIGHT,:LYCANROC_DUSK,:TOXAPEX,:MUDSDALE,:ARAQUANID,:LURANTIS,:SHIINOTIC,:SALAZZLE,:BEWEAR,:TSAREENA,:COMFEY,:ORANGURU,:PASSIMIAN,:GOLISOPOD,:PALOSSAND,:PYUKUMUKU,:SILVALLY,:ORICORIO_BAILE,:ORICORIO_POMPOM,:ORICORIO_PAU,:ORICORIO_SENSU,:MINIOR,:KOMALA,:TURTONATOR,:TOGEDEMARU,:MIMIKYU,:BRUXISH,:DRAMPA,:DHELMISE,:KOMMOO,:RILLABOOM,:CINDERACE,:INTELEON,:GREEDENT,:CORVIKNIGHT,:ORBEETLE,:THIEVUL,:ELDEGOSS,:DUBWOOL,:DREDNAW,:BOLTUND,:COALOSSAL,:FLAPPLE,:APPLETUN,:SANDACONDA,:CRAMORANT,:BARRASKEWDA,:TOXTRICITY,:CENTISKORCH,:GRAPPLOCT,:POLTEAGEIST,:HATTERENE,:GRIMMSNARL,:OBSTAGOON,:PERRSERKER,:CURSOLA,:SIRFETCHD,:MRRIME,:RUNERIGUS,:ALCREMIE,:FALINKS,:PINCURCHIN,:FROSMOTH,:STONJOURNER,:EISCUE,:INDEEDEE,:MORPEKO,:COPPERAJAH,:DRACOZOLT,:ARCTOZOLT,:DRACOVISH,:ARCTOVISH,:DURALUDON,:DRAGAPULT,:WYRDEER,:KLEAVOR,:URSALUNA,:BASCULEGION,:SNEASLER,:OVERQWIL,:MEOWSCARADA,:SKELEDIRGE,:QUAQUAVAL,:OINKOLOGNE,:SPIDOPS,:LOKIX,:PAWMOT,:MAUSHOLD,:DACHSBUN,:ARBOLIVA,:SQUAWKABILLY,:GARGANACL,:ARMAROUGE,:CERULEDGE,:BELLIBOLT,:KILOWATTREL,:MABOSSTIFF,:GRAFAIAI,:BRAMBLEGHAST,:TOEDSCRUEL,:KLAWF,:SCOVILLAIN,:RABSCA,:ESPATHRA,:TINKATON,:WUGTRIO,:BOMBIRDIER,:PALAFIN,:REVAVROOM,:CYCLIZAR,:ORTHWORM,:GLIMMORA,:HOUNDSTONE,:FLAMIGO,:CETITAN,:VELUZA,:DONDOZO,:TATSUGIRI,:ANNIHILAPE,:CLODSIRE,:FARIGIRAF,:DUDUNSPARCE,:KINGAMBIT,:BAXCALIBUR]
	
	def self.allspecies
		return @allspecies
	end

	VENUSAUR = {:species => :VENUSAUR, :region => Kanto, :moves => [:PETALDANCE, :ENERGYBALL, :SLUDGEBOMB, :TOXIC], :form => 0, :ability_index => 0}
	CHARIZARD = {:species => :CHARIZARD, :region => Kanto, :moves => [:DRAGONPULSE, :FLAMETHROWER, :AIRSLASH, :OVERHEAT], :form => 0, :ability_index => 0}
	BLASTOISE = {:species => :BLASTOISE, :region => Kanto, :moves => [:AQUATAIL, :SURF, :FLASHCANNON, :SHELLSMASH], :form => 0, :ability_index => 0}
	BUTTERFREE = {:species => :BUTTERFREE, :region => Kanto, :moves => [:BUGBUZZ, :PSYCHIC, :POISONPOWDER, :AIRSLASH], :form => 0, :ability_index => 0}
	BEEDRILL = {:species => :BEEDRILL, :region => Kanto, :moves => [:POISONJAB, :BUGBITE, :ENDEAVOR, :ASSURANCE], :form => 0, :ability_index => 0}
	PIDGEOT = {:species => :PIDGEOT, :region => Kanto, :moves => [:AIRSLASH, :ROOST, :AERIALACE, :QUICKATTACK], :form => 0, :ability_index => 1}
	RATICATE = {:species => :RATICATE, :region => Kanto, :moves => [:QUICKATTACK, :CRUNCH, :SWORDSDANCE, :DIG], :form => 0, :ability_index => 1}
	RATICATE_ALOLA = {:species => :RATICATE, :region => Alola, :moves => [:CRUNCH, :SUCKERPUNCH, :DOUBLEEDGE, :SCARYFACE], :form => 1, :ability_index => 1}
	FEAROW = {:species => :FEAROW, :region => Kanto, :moves => [:DRILLRUN, :AERIALACE, :UTURN, :STEELWING], :form => 0, :ability_index => 0}
	ARBOK = {:species => :ARBOK, :region => Kanto, :moves => [:CRUNCH, :GUNKSHOT, :ICEFANG, :GLARE], :form => 0, :ability_index => 0}
	RAICHU = {:species => :RAICHU, :region => Kanto, :moves => [:THUNDER, :RAINDANCE, :THUNDERBOLT, :SURF], :form => 0, :ability_index => 0}
	RAICHU_ALOLA = {:species => :RAICHU, :region => Alola, :moves => [:PSYCHIC, :THUNDERBOLT, :DRAININGKISS, :SURF], :form => 1, :ability_index => 0}
	SANDSLASH = {:species => :SANDSLASH, :region => Kanto, :moves => [:EARTHQUAKE, :ROLLOUT, :SWORDSDANCE, :SLASH], :form => 0, :ability_index => 0}
	SANDSLASH_ALOLA = {:species => :SANDSLASH, :region => Alola, :moves => [:IRONHEAD, :ICICLECRASH, :ICICLESPEAR, :IRONDEFENSE], :form => 1, :ability_index => 0}
	NIDOQUEEN = {:species => :NIDOQUEEN, :region => Kanto, :moves => [:TOXICSPIKES, :CRUNCH, :EARTHPOWER, :SUPERPOWER], :form => 0, :ability_index => 0}
	NIDOKING = {:species => :NIDOKING, :region => Kanto, :moves => [:POISONJAB, :EARTHQUAKE, :MEGAHORN, :TOXIC], :form => 0, :ability_index => 0}
	CLEFABLE = {:species => :CLEFABLE, :region => Kanto, :moves => [:MOONBLAST, :METRONOME, :PSYCHIC, :FLAMETHROWER], :form => 0, :ability_index => 1}
	NINETALES = {:species => :NINETALES, :region => Kanto, :moves => [:FLAMETHROWER, :WILLOWISP, :DISABLE, :ENERGYBALL], :form => 0, :ability_index => 0}
	NINETALES_ALOLA = {:species => :NINETALES, :region => Alola, :moves => [:DAZZLINGGLEAM, :ICEBEAM, :NASTYPLOT, :SHADOWBALL], :form => 1, :ability_index => 0}
	WIGGLYTUFF = {:species => :WIGGLYTUFF, :region => Kanto, :moves => [:PLAYROUGH, :PSYCHIC, :THUNDERBOLT, :MIMIC], :form => 0, :ability_index => 1}
	VILEPLUME = {:species => :VILEPLUME, :region => Kanto, :moves => [:GIGADRAIN, :PETALDANCE, :SLUDGEWAVE, :DAZZLINGGLEAM], :form => 0, :ability_index => 0}
	PARASECT = {:species => :PARASECT, :region => Kanto, :moves => [:CROSSPOISON, :XSCISSOR, :STUNSPORE, :POISONPOWDER], :form => 0, :ability_index => 0}
	VENOMOTH = {:species => :VENOMOTH, :region => Kanto, :moves => [:BUGBUZZ, :ENERGYBALL, :SLUDGEBOMB, :PROTECT], :form => 0, :ability_index => 1}
	DUGTRIO = {:species => :DUGTRIO, :region => Kanto, :moves => [:SANDTOMB, :NIGHTSLASH, :EARTHQUAKE, :SANDSTORM], :form => 0, :ability_index => 0}
	DUGTRIO_ALOLA = {:species => :DUGTRIO, :region => Alola, :moves => [:IRONHEAD, :DIG, :EARTHQUAKE, :SUCKERPUNCH], :form => 1, :ability_index => 1}
	PERSIAN = {:species => :PERSIAN, :region => Kanto, :moves => [:ASSURANCE, :SLASH, :PLAYROUGH, :DIG], :form => 0, :ability_index => 0}
	PERSIAN_ALOLA = {:species => :PERSIAN, :region => Alola, :moves => [:POWERGEM, :THUNDERBOLT, :SHADOWBALL, :DARKPULSE], :form => 1, :ability_index => 0}
	GOLDUCK = {:species => :GOLDUCK, :region => Kanto, :moves => [:HYDROPUMP, :SURF, :PSYCHIC, :CALMMIND], :form => 0, :ability_index => 1}
	PRIMEAPE = {:species => :PRIMEAPE, :region => Kanto, :moves => [:OUTRAGE, :STOMPINGTANTRUM, :CLOSECOMBAT, :SWAGGER], :form => 0, :ability_index => 0}
	ARCANINE = {:species => :ARCANINE, :region => Kanto, :moves => [:FLAMETHROWER, :FLAREBLITZ, :EXTREMESPEED, :PLAYROUGH], :form => 0, :ability_index => 0}
	POLIWRATH = {:species => :POLIWRATH, :region => Kanto, :moves => [:DRAINPUNCH, :DIVE, :EARTHQUAKE, :POISONJAB], :form => 0, :ability_index => 0}
	ALAKAZAM = {:species => :ALAKAZAM, :region => Kanto, :moves => [:PSYCHIC, :CALMMIND, :DAZZLINGGLEAM, :SHADOWBALL], :form => 0, :ability_index => 0}
	MACHAMP = {:species => :MACHAMP, :region => Kanto, :moves => [:STONEEDGE, :DARKESTLARIAT, :CLOSECOMBAT, :BRICKBREAK], :form => 0, :ability_index => 0}
	VICTREEBEL = {:species => :VICTREEBEL, :region => Kanto, :moves => [:LEAFTORNADO, :LEAFBLADE, :POISONJAB, :SLEEPPOWDER], :form => 0, :ability_index => 0}
	TENTACRUEL = {:species => :TENTACRUEL, :region => Kanto, :moves => [:SLUDGEWAVE, :SURF, :HEX, :SCALD], :form => 0, :ability_index => 1}
	GOLEM = {:species => :GOLEM, :region => Kanto, :moves => [:EARTHQUAKE, :STONEEDGE, :HEAVYSLAM, :SANDSTORM], :form => 0, :ability_index => 1}
	GOLEM_ALOLA = {:species => :GOLEM, :region => Alola, :moves => [:STONEEDGE, :THUNDERPUNCH, :EARTHQUAKE, :GYROBALL], :form => 1, :ability_index => 1}
	RAPIDASH = {:species => :RAPIDASH, :region => Kanto, :moves => [:SMARTSTRIKE, :FLAMEWHEEL, :FLAREBLITZ, :POISONJAB], :form => 0, :ability_index => 1}
	RAPIDASH_GALAR = {:species => :RAPIDASH, :region => Galar, :moves => [:PSYCHOCUT, :DRILLRUN, :MEGAHORN, :PLAYROUGH], :form => 1, :ability_index => 1}
	SLOWBRO = {:species => :SLOWBRO, :region => Kanto, :moves => [:SURF, :PSYCHIC, :SHADOWBALL, :PROTECT], :form => 0, :ability_index => 1}
	SLOWBRO_GALAR = {:species => :SLOWBRO, :region => Galar, :moves => [:SHELLSIDEARM, :SURF, :PSYCHIC, :ZENHEADBUTT], :form => 1, :ability_index => 0}
	FARFETCHD = {:species => :FARFETCHD, :region => Kanto, :moves => [:LUNGE, :DRILLPECK, :FLY, :STEELWING], :form => 0, :ability_index => 1}
	DODRIO = {:species => :DODRIO, :region => Kanto, :moves => [:LUNGE, :DRILLPECK, :FLY, :STEELWING], :form => 0, :ability_index => 1}
	DEWGONG = {:species => :DEWGONG, :region => Kanto, :moves => [:ICEBEAM, :AQUATAIL, :ICESHARD, :AQUARING], :form => 0, :ability_index => 0}
	MUK = {:species => :MUK, :region => Kanto, :moves => [:SLUDGEWAVE, :SLUDGEBOMB, :DARKPULSE, :FLAMETHROWER], :form => 0, :ability_index => 0}
	MUK_ALOLA = {:species => :MUK, :region => Alola, :moves => [:GUNKSHOT, :KNOCKOFF, :TOXIC, :VENOMDRENCH], :form => 1, :ability_index => 0}
	CLOYSTER = {:species => :CLOYSTER, :region => Kanto, :moves => [:ICICLESPEAR, :SURF, :ROCKBLAST, :PINMISSILE], :form => 0, :ability_index => 1}
	GENGAR = {:species => :GENGAR, :region => Kanto, :moves => [:DARKPULSE, :SHADOWBALL, :SLUDGEBOMB, :THUNDERBOLT], :form => 0, :ability_index => 0}
	HYPNO = {:species => :HYPNO, :region => Kanto, :moves => [:PSYCHIC, :HYPNOSIS, :DREAMEATER, :SHADOWBALL], :form => 0, :ability_index => 1}
	KINGLER = {:species => :KINGLER, :region => Kanto, :moves => [:CRABHAMMER, :METALCLAW, :STOMPINGTANTRUM, :XSCISSOR], :form => 0, :ability_index => 0}
	ELECTRODE = {:species => :ELECTRODE, :region => Kanto, :moves => [:DISCHARGE, :THUNDERBOLT, :LIGHTSCREEN, :THUNDERWAVE], :form => 0, :ability_index => 1}
	EXEGGUTOR = {:species => :EXEGGUTOR, :region => Kanto, :moves => [:PSYSHOCK, :GIGADRAIN, :LEAFSTORM, :SLUDGEBOMB], :form => 0, :ability_index => 0}
	EXEGGUTOR_ALOLA = {:species => :EXEGGUTOR, :region => Alola, :moves => [:DRAGONHAMMER, :GIGADRAIN, :LEAFSTORM, :DRAGONPULSE], :form => 1, :ability_index => 0}
	MAROWAK = {:species => :MAROWAK, :region => Kanto, :moves => [:GIGAIMPACT, :BONEMERANG, :ROCKTOMB, :EARTHQUAKE], :form => 0, :ability_index => 0}
	MAROWAK_ALOLA = {:species => :MAROWAK, :region => Alola, :moves => [:SHADOWBONE, :STOMPINGTANTRUM, :FLAREBLITZ, :FLAMEWHEEL], :form => 1, :ability_index => 0}
	HITMONLEE = {:species => :HITMONLEE, :region => Kanto, :moves => [:BLAZEKICK, :BRICKBREAK, :POISONJAB, :THROATCHOP], :form => 0, :ability_index => 0}
	HITMONCHAN = {:species => :HITMONCHAN, :region => Kanto, :moves => [:DRAINPUNCH, :POWERUPPUNCH, :THUNDERPUNCH, :BULLETPUNCH], :form => 0, :ability_index => 1}
	WEEZING = {:species => :WEEZING, :region => Kanto, :moves => [:ASSURANCE, :TOXIC, :SLUDGEBOMB, :HEATWAVE], :form => 0, :ability_index => 0}
	WEEZING_GALAR = {:species => :WEEZING, :region => Galar, :moves => [:STRANGESTEAM, :SLUDGEBOMB, :MISTYTERRAIN, :THUNDERBOLT], :form => 1, :ability_index => 1}
	KANGASKHAN = {:species => :KANGASKHAN, :region => Kanto, :moves => [:OUTRAGE, :BRICKBREAK, :DRAINPUNCH, :BODYSLAM], :form => 0, :ability_index => 1}
	SEAKING = {:species => :SEAKING, :region => Kanto, :moves => [:WATERFALL, :MEGAHORN, :RAINDANCE, :SMARTSTRIKE], :form => 0, :ability_index => 0}
	STARMIE = {:species => :STARMIE, :region => Kanto, :moves => [:PSYCHIC, :HYDROPUMP, :POWERGEM, :RECOVER], :form => 0, :ability_index => 1}
	MRMIME = {:species => :MRMIME, :region => Kanto, :moves => [:PSYCHIC, :DAZZLINGGLEAM, :MAGICALLEAF, :CALMMIND], :form => 0, :ability_index => 1}
	JYNX = {:species => :JYNX, :region => Kanto, :moves => [:PSYCHIC, :BLIZZARD, :ICEBEAM, :SHADOWBALL], :form => 0, :ability_index => 0}
	PINSIR = {:species => :PINSIR, :region => Kanto, :moves => [:SUPERPOWER, :XSCISSOR, :SWORDSDANCE, :SUBMISSION], :form => 0, :ability_index => 0}
	TAUROS = {:species => :TAUROS, :region => Kanto, :moves => [:ASSURANCE, :ZENHEADBUTT, :STOMPINGTANTRUM, :STONEEDGE], :form => 0, :ability_index => 0}
	TAUROS_PALDEACOMBAT = {:species => :TAUROS, :region => Paldea, :moves => [:ASSURANCE, :ZENHEADBUTT, :STOMPINGTANTRUM, :STONEEDGE], :form => 1, :ability_index => 0}
	TAUROS_PALDEABLAZE = {:species => :TAUROS, :region => Paldea, :moves => [:ASSURANCE, :ZENHEADBUTT, :STOMPINGTANTRUM, :STONEEDGE], :form => 2, :ability_index => 0}
	TAUROS_PALDEAAQUA = {:species => :TAUROS, :region => Paldea, :moves => [:ASSURANCE, :ZENHEADBUTT, :STOMPINGTANTRUM, :STONEEDGE], :form => 3, :ability_index => 0}
	GYARADOS = {:species => :GYARADOS, :region => Kanto, :moves => [:ICEFANG, :BOUNCE, :OUTRAGE, :AQUATAIL], :form => 0, :ability_index => 0}
	LAPRAS = {:species => :LAPRAS, :region => Kanto, :moves => [:ICEBEAM, :BRINE, :RAINDANCE, :SING], :form => 0, :ability_index => 0}
	DITTO = {:species => :DITTO, :region => Kanto, :moves => [:TRANSFORM, nil, nil, nil], :form => 0, :ability_index => 0}
	VAPOREON = {:species => :VAPOREON, :region => Kanto, :moves => [:BRINE, :ICEBEAM, :SHADOWBALL, :AQUARING], :form => 0, :ability_index => 0}
	JOLTEON = {:species => :JOLTEON, :region => Kanto, :moves => [:THUNDERBOLT, :THUNDER, :SHADOWBALL, :RAINDANCE], :form => 0, :ability_index => 0}
	FLAREON = {:species => :FLAREON, :region => Kanto, :moves => [:FLAREBLITZ, :BITE, :IRONTAIL, :SUPERPOWER], :form => 0, :ability_index => 0}
	OMASTAR = {:species => :OMASTAR, :region => Kanto, :moves => [:BRINE, :ANCIENTPOWER, :EARTHPOWER, :SCALD], :form => 0, :ability_index => 0}
	KABUTOPS = {:species => :KABUTOPS, :region => Kanto, :moves => [:AQUAJET, :LIQUIDATION, :LEECHLIFE, :STONEEDGE], :form => 0, :ability_index => 0}
	AERODACTYL = {:species => :AERODACTYL, :region => Kanto, :moves => [:GIGAIMPACT, :ROCKSLIDE, :STONEEDGE, :IRONHEAD], :form => 0, :ability_index => 0}
	SNORLAX = {:species => :SNORLAX, :region => Kanto, :moves => [:HAMMERARM, :HIGHHORSEPOWER, :HEAVYSLAM, :BODYSLAM], :form => 0, :ability_index => 0}
	DRAGONITE = {:species => :DRAGONITE, :region => Kanto, :moves => [:OUTRAGE, :THUNDERPUNCH, :STONEEDGE, :DRAGONDANCE], :form => 0, :ability_index => 0}
	MEGANIUM = {:species => :MEGANIUM, :region => Johto, :moves => [:DRAGONTAIL, :SYNTHESIS, :AROMATHERAPY, :GIGADRAIN], :form => 0, :ability_index => 0}
	TYPHLOSION = {:species => :TYPHLOSION, :region => Johto, :moves => [:FLAMETHROWER, :ERUPTION, :FOCUSBLAST, :SUNNYDAY], :form => 0, :ability_index => 0}
	FERALIGATR = {:species => :FERALIGATR, :region => Johto, :moves => [:DRAGONDANCE, :WATERFALL, :CRUNCH, :ICEPUNCH], :form => 0, :ability_index => 0}
	FURRET = {:species => :FURRET, :region => Johto, :moves => [:SLAM, :FACADE, :IRONTAIL, :REST], :form => 0, :ability_index => 1}
	NOCTOWL = {:species => :NOCTOWL, :region => Johto, :moves => [:AIRSLASH, :HYPNOSIS, :DREAMEATER, :MOONBLAST], :form => 0, :ability_index => 1}
	LEDIAN = {:species => :LEDIAN, :region => Johto, :moves => [:BUGBUZZ, :AIRSLASH, :REFLECT, :LIGHTSCREEN], :form => 0, :ability_index => 1}
	ARIADOS = {:species => :ARIADOS, :region => Johto, :moves => [:LEECHLIFE, :POISONJAB, :CROSSPOISON, :SHADOWSNEAK], :form => 0, :ability_index => 0}
	CROBAT = {:species => :CROBAT, :region => Johto, :moves => [:LEECHLIFE, :CROSSPOISON, :BRAVEBIRD, :ZENHEADBUTT], :form => 0, :ability_index => 0}
	LANTURN = {:species => :LANTURN, :region => Johto, :moves => [:SCALD, :VOLTSWITCH, :TOXIC, :PROTECT], :form => 0, :ability_index => 0}
	XATU = {:species => :XATU, :region => Johto, :moves => [:PSYCHIC, :HEATWAVE, :ROOST, :TELEPORT], :form => 0, :ability_index => 0}
	AMPHAROS = {:species => :AMPHAROS, :region => Johto, :moves => [:DRAGONPULSE, :POWERGEM, :DISCHARGE, :LIGHTSCREEN], :form => 0, :ability_index => 0}
	BELLOSSOM = {:species => :BELLOSSOM, :region => Johto, :moves => [:MOONBLAST, :SOLARBEAM, :GIGADRAIN, :MOONLIGHT], :form => 0, :ability_index => 0}
	AZUMARILL = {:species => :AZUMARILL, :region => Johto, :moves => [:AQUATAIL, :PLAYROUGH, :BULLDOZE, :BOUNCE], :form => 0, :ability_index => 1}
	SUDOWOODO = {:species => :SUDOWOODO, :region => Johto, :moves => [:STEALTHROCK, :STONEEDGE, :WOODHAMMER, :SUCKERPUNCH], :form => 0, :ability_index => 0}
	POLITOED = {:species => :POLITOED, :region => Johto, :moves => [:REST, :TOXIC, :SCALD, :PROTECT], :form => 0, :ability_index => 0}
	JUMPLUFF = {:species => :JUMPLUFF, :region => Johto, :moves => [:SWORDSDANCE, :GIGADRAIN, :LEECHSEED, :POISONPOWDER], :form => 0, :ability_index => 1}
	SUNFLORA = {:species => :SUNFLORA, :region => Johto, :moves => [:PETALDANCE, :SUNNYDAY, :SOLARBEAM, :SLUDGEBOMB], :form => 0, :ability_index => 0}
	QUAGSIRE = {:species => :QUAGSIRE, :region => Johto, :moves => [:EARTHQUAKE, :AQUATAIL, :BRICKBREAK, :ROCKTOMB], :form => 0, :ability_index => 1}
	ESPEON = {:species => :ESPEON, :region => Johto, :moves => [:PSYCHIC, :DAZZLINGGLEAM, :SHADOWBALL, :REST], :form => 0, :ability_index => 0}
	UMBREON = {:species => :UMBREON, :region => Johto, :moves => [:FOULPLAY, :WISH, :PROTECT, :HEALBELL], :form => 0, :ability_index => 0}
	SLOWKING = {:species => :SLOWKING, :region => Johto, :moves => [:SCALD, :PSYCHIC, :SLACKOFF, :TELEPORT], :form => 0, :ability_index => 1}
	SLOWKING_GALAR = {:species => :SLOWKING, :region => Galar, :moves => [:PSYCHIC, :SLUDGEBOMB, :FLAMETHROWER, :ICEBEAM], :form => 1, :ability_index => 0}
	WOBBUFFET = {:species => :WOBBUFFET, :region => Johto, :moves => [:DESTINYBOND, :COUNTER, :ENCORE, :MIRRORCOAT], :form => 0, :ability_index => 0}
	GIRAFARIG = {:species => :GIRAFARIG, :region => Johto, :moves => [:ZENHEADBUTT, :EARTHQUAKE, :CRUNCH, :PROTECT], :form => 0, :ability_index => 0}
	FORRETRESS = {:species => :FORRETRESS, :region => Johto, :moves => [:HEAVYSLAM, :GYROBALL, :SPIKES, :TOXICSPIKES], :form => 0, :ability_index => 0}
	STEELIX = {:species => :STEELIX, :region => Johto, :moves => [:STEALTHROCK, :EARTHQUAKE, :HEAVYSLAM, :TOXIC], :form => 0, :ability_index => 1}
	GRANBULL = {:species => :GRANBULL, :region => Johto, :moves => [:PLAYROUGH, :OUTRAGE, :CRUNCH, :TAUNT], :form => 0, :ability_index => 0}
	SCIZOR = {:species => :SCIZOR, :region => Johto, :moves => [:BULLETPUNCH, :IRONHEAD, :XSCISSOR, :SWORDSDANCE], :form => 0, :ability_index => 1}
	SHUCKLE = {:species => :SHUCKLE, :region => Johto, :moves => [:BULLETPUNCH, :IRONHEAD, :XSCISSOR, :SWORDSDANCE], :form => 0, :ability_index => 1}
	HERACROSS = {:species => :HERACROSS, :region => Johto, :moves => [:FACADE, :THROATCHOP, :MEGAHORN, :CLOSECOMBAT], :form => 0, :ability_index => 1}
	MAGCARGO = {:species => :MAGCARGO, :region => Johto, :moves => [:STEALTHROCK, :TOXIC, :LAVAPLUME, :RECOVER], :form => 0, :ability_index => 1}
	URSARING = {:species => :URSARING, :region => Johto, :moves => [:SWORDSDANCE, :FACADE, :CRUNCH, :CLOSECOMBAT], :form => 0, :ability_index => 0}
	OCTILLERY = {:species => :OCTILLERY, :region => Johto, :moves => [:SURF, :FIREBLAST, :ICEBEAM, :ENERGYBALL], :form => 0, :ability_index => 1}
	MANTINE = {:species => :MANTINE, :region => Johto, :moves => [:SCALD, :ROOST, :AIRSLASH, :ICEBEAM], :form => 0, :ability_index => 1}
	SKARMORY = {:species => :SKARMORY, :region => Johto, :moves => [:WHIRLWIND, :ROOST, :BRAVEBIRD, :SPIKES], :form => 0, :ability_index => 1}
	HOUNDOOM = {:species => :HOUNDOOM, :region => Johto, :moves => [:FLAMETHROWER, :DARKPULSE, :SHADOWBALL, :TAUNT], :form => 0, :ability_index => 0}
	KINGDRA = {:species => :KINGDRA, :region => Johto, :moves => [:HYDROPUMP, :DRACOMETEOR, :SURF, :RAINDANCE], :form => 0, :ability_index => 0}
	DONPHAN = {:species => :DONPHAN, :region => Johto, :moves => [:EARTHQUAKE, :RAPIDSPIN, :KNOCKOFF, :STEALTHROCK], :form => 0, :ability_index => 0}
	HITMONTOP = {:species => :HITMONTOP, :region => Johto, :moves => [:DIG, :CLOSECOMBAT, :SUCKERPUNCH, :DETECT], :form => 0, :ability_index => 0}
	MILTANK = {:species => :MILTANK, :region => Johto, :moves => [:STEALTHROCK, :MILKDRINK, :THUNDERWAVE, :SEISMICTOSS], :form => 0, :ability_index => 0}
	BLISSEY = {:species => :BLISSEY, :region => Johto, :moves => [:SEISMICTOSS, :SOFTBOILED, :THUNDERWAVE, :TELEPORT], :form => 0, :ability_index => 0}
	TYRANITAR = {:species => :TYRANITAR, :region => Johto, :moves => [:STEALTHROCK, :ROCKBLAST, :EARTHQUAKE, :THUNDERWAVE], :form => 0, :ability_index => 0}
	SCEPTILE = {:species => :SCEPTILE, :region => Hoenn, :moves => [:GIGADRAIN, :ENERGYBALL, :DRAGONPULSE, :FOCUSBLAST], :form => 0, :ability_index => 0}
	BLAZIKEN = {:species => :BLAZIKEN, :region => Hoenn, :moves => [:BLAZEKICK, :CLOSECOMBAT, :AERIALACE, :DETECT], :form => 0, :ability_index => 0}
	SWAMPERT = {:species => :SWAMPERT, :region => Hoenn, :moves => [:HAMMERARM, :EARTHQUAKE, :LIQUIDATION, :ROCKSLIDE], :form => 0, :ability_index => 0}
	MIGHTYENA = {:species => :MIGHTYENA, :region => Hoenn, :moves => [:FIREFANG, :THUNDERFANG, :ICEFANG, :CRUNCH], :form => 0, :ability_index => 0}
	BEAUTIFLY = {:species => :BEAUTIFLY, :region => Hoenn, :moves => [:GIGADRAIN, :PROTECT, :QUIVERDANCE, :BUGBUZZ], :form => 0, :ability_index => 0}
	DUSTOX = {:species => :DUSTOX, :region => Hoenn, :moves => [:TOXIC, :VENOSHOCK, :LEECHLIFE, :PROTECT], :form => 0, :ability_index => 0}
	LUDICOLO = {:species => :LUDICOLO, :region => Hoenn, :moves => [:GIGADRAIN, :HYDROPUMP, :ICEBEAM, :RAINDANCE], :form => 0, :ability_index => 0}
	SHIFTRY = {:species => :SHIFTRY, :region => Hoenn, :moves => [:LEAFBLADE, :FOULPLAY, :LOWSWEEP, :PROTECT], :form => 0, :ability_index => 1}
	SWELLOW = {:species => :SWELLOW, :region => Hoenn, :moves => [:BRAVEBIRD, :AERIALACE, :QUICKATTACK, :UTURN], :form => 0, :ability_index => 0}
	PELIPPER = {:species => :PELIPPER, :region => Hoenn, :moves => [:SCALD, :ROOST, :UTURN, :DEFOG], :form => 0, :ability_index => 1}
	GARDEVOIR = {:species => :GARDEVOIR, :region => Hoenn, :moves => [:MOONBLAST, :PSYCHIC, :MYSTICALFIRE, :HEALINGWISH], :form => 0, :ability_index => 1}
	MASQUERAIN = {:species => :MASQUERAIN, :region => Hoenn, :moves => [:STICKYWEB, :BUGBUZZ, :AIRSLASH, :SCALD], :form => 0, :ability_index => 0}
	BRELOOM = {:species => :BRELOOM, :region => Hoenn, :moves => [:DRAINPUNCH, :SEEDBOMB, :MACHPUNCH, :STONEEDGE], :form => 0, :ability_index => 1}
	SLAKING = {:species => :SLAKING, :region => Hoenn, :moves => [:EARTHQUAKE, :FIREBLAST, :RETALIATE, :SUCKERPUNCH], :form => 0, :ability_index => 0}
	NINJASK = {:species => :NINJASK, :region => Hoenn, :moves => [:XSCISSOR, :METALCLAW, :AERIALACE, :PROTECT], :form => 0, :ability_index => 0}
	SHEDINJA = {:species => :SHEDINJA, :region => Hoenn, :moves => [:SHADOWCLAW, :DIG, :PHANTOMFORCE, :SPITE], :form => 0, :ability_index => 0}
	EXPLOUD = {:species => :EXPLOUD, :region => Hoenn, :moves => [:BOOMBURST, :OVERHEAT, :SURF, :FOCUSBLAST], :form => 0, :ability_index => 0}
	HARIYAMA = {:species => :HARIYAMA, :region => Hoenn, :moves => [:CLOSECOMBAT, :KNOCKOFF, :HEAVYSLAM, :STONEEDGE], :form => 0, :ability_index => 0}
	DELCATTY = {:species => :DELCATTY, :region => Hoenn, :moves => [:PLAYROUGH, :FAKEOUT, :STRENGTH, :FACADE], :form => 0, :ability_index => 0}
	SABLEYE = {:species => :SABLEYE, :region => Hoenn, :moves => [:KNOCKOFF, :RECOVER, :WILLOWISP, :ENCORE], :form => 0, :ability_index => 0}
	MAWILE = {:species => :MAWILE, :region => Hoenn, :moves => [:SWORDSDANCE, :PLAYROUGH, :SUCKERPUNCH, :KNOCKOFF], :form => 0, :ability_index => 1}
	AGGRON = {:species => :AGGRON, :region => Hoenn, :moves => [:STEALTHROCK, :HEADSMASH, :HEAVYSLAM, :PROTECT], :form => 0, :ability_index => 1}
	MEDICHAM = {:species => :MEDICHAM, :region => Hoenn, :moves => [:FAKEOUT, :HIGHJUMPKICK, :ZENHEADBUTT, :BULLETPUNCH], :form => 0, :ability_index => 0}
	MANECTRIC = {:species => :MANECTRIC, :region => Hoenn, :moves => [:THUNDERBOLT, :VOLTSWITCH, :ELECTRICTERRAIN, :FLAMETHROWER], :form => 0, :ability_index => 0}
	SWALOT = {:species => :SWALOT, :region => Hoenn, :moves => [:SLUDGEBOMB, :TOXIC, :SHADOWBALL, :EARTHQUAKE], :form => 0, :ability_index => 1}
	SHARPEDO = {:species => :SHARPEDO, :region => Hoenn, :moves => [:WATERFALL, :CRUNCH, :CLOSECOMBAT, :PROTECT], :form => 0, :ability_index => 0}
	WAILORD = {:species => :WAILORD, :region => Hoenn, :moves => [:SUBSTITUTE, :AQUARING, :PROTECT, :BLOCK], :form => 0, :ability_index => 0}
	CAMERUPT = {:species => :CAMERUPT, :region => Hoenn, :moves => [:FIREBLAST, :EARTHPOWER, :REST, :SLEEPTALK], :form => 0, :ability_index => 1}
	TORKOAL = {:species => :TORKOAL, :region => Hoenn, :moves => [:STEALTHROCK, :LAVAPLUME, :RAPIDSPIN, :TOXIC], :form => 0, :ability_index => 1}
	GRUMPIG = {:species => :GRUMPIG, :region => Hoenn, :moves => [:PSYCHIC, :FOCUSBLAST, :SHADOWBALL, :CALMMIND], :form => 0, :ability_index => 0}
	FLYGON = {:species => :FLYGON, :region => Hoenn, :moves => [:DRAGONDANCE, :EARTHQUAKE, :OUTRAGE, :STONEEDGE], :form => 0, :ability_index => 0}
	CACTURNE = {:species => :CACTURNE, :region => Hoenn, :moves => [:SPIKES, :GIGADRAIN, :DARKPULSE, :SUCKERPUNCH], :form => 0, :ability_index => 0}
	ALTARIA = {:species => :ALTARIA, :region => Hoenn, :moves => [:DEFOG, :ROOST, :HURRICANE, :FLAMETHROWER], :form => 0, :ability_index => 0}
	ZANGOOSE = {:species => :ZANGOOSE, :region => Hoenn, :moves => [:FACADE, :SWORDSDANCE, :CLOSECOMBAT, :XSCISSOR], :form => 0, :ability_index => 0}
	SEVIPER = {:species => :SEVIPER, :region => Hoenn, :moves => [:SLUDGEWAVE, :GIGADRAIN, :FLAMETHROWER, :SUCKERPUNCH], :form => 0, :ability_index => 0}
	LUNATONE = {:species => :LUNATONE, :region => Hoenn, :moves => [:METEORBEAM, :PSYSHOCK, :EARTHPOWER, :ROCKPOLISH], :form => 0, :ability_index => 0}
	SOLROCK = {:species => :SOLROCK, :region => Hoenn, :moves => [:STEALTHROCK, :MORNINGSUN, :WILLOWISP, :ZENHEADBUTT], :form => 0, :ability_index => 0}
	WHISCASH = {:species => :WHISCASH, :region => Hoenn, :moves => [:AQUATAIL, :EARTHQUAKE, :THRASH, :ZENHEADBUTT], :form => 0, :ability_index => 1}
	CRAWDAUNT = {:species => :CRAWDAUNT, :region => Hoenn, :moves => [:SWORDSDANCE, :CRABHAMMER, :KNOCKOFF, :AQUAJET], :form => 0, :ability_index => 0}
	CLAYDOL = {:species => :CLAYDOL, :region => Hoenn, :moves => [:PSYCHIC, :SCORCHINGSANDS, :PROTECT, :TELEPORT], :form => 0, :ability_index => 0}
	CRADILY = {:species => :CRADILY, :region => Hoenn, :moves => [:STEALTHROCK, :RECOVER, :TOXIC, :GIGADRAIN], :form => 0, :ability_index => 0}
	ARMALDO = {:species => :ARMALDO, :region => Hoenn, :moves => [:METALCLAW, :XSCISSOR, :STONEEDGE, :PROTECT], :form => 0, :ability_index => 0}
	MILOTIC = {:species => :MILOTIC, :region => Hoenn, :moves => [:SCALD, :RECOVER, :ICEBEAM, :TOXIC], :form => 0, :ability_index => 0}
	BANETTE = {:species => :BANETTE, :region => Hoenn, :moves => [:DESTINYBOND, :SHADOWCLAW, :GUNKSHOT, :KNOCKOFF], :form => 0, :ability_index => 0}
	TROPIUS = {:species => :TROPIUS, :region => Hoenn, :moves => [:LEECHSEED, :SUBSTITUTE, :AIRSLASH, :PROTECT], :form => 0, :ability_index => 1}
	CHIMECHO = {:species => :CHIMECHO, :region => Hoenn, :moves => [:HEALINGWISH, :RECOVER, :PSYCHIC, :THUNDERWAVE], :form => 0, :ability_index => 0}
	ABSOL = {:species => :ABSOL, :region => Hoenn, :moves => [:SWORDSDANCE, :KNOCKOFF, :SUCKERPUNCH, :PLAYROUGH], :form => 0, :ability_index => 1}
	GLALIE = {:species => :GLALIE, :region => Hoenn, :moves => [:HAIL, :CRUNCH, :BLIZZARD, :ICEBEAM], :form => 0, :ability_index => 1}
	WALREIN = {:species => :WALREIN, :region => Hoenn, :moves => [:SWORDSDANCE, :WATERFALL, :ICICLESPEAR, :EARTHQUAKE], :form => 0, :ability_index => 0}
	HUNTAIL = {:species => :HUNTAIL, :region => Hoenn, :moves => [:SHELLSMASH, :WATERFALL, :SUCKERPUNCH, :ICEBEAM], :form => 0, :ability_index => 0}
	GOREBYSS = {:species => :GOREBYSS, :region => Hoenn, :moves => [:SHELLSMASH, :HYDROPUMP, :ICEBEAM, :SUBSTITUTE], :form => 0, :ability_index => 0}
	RELICANTH = {:species => :RELICANTH, :region => Hoenn, :moves => [:HEADSMASH, :WATERFALL, :EARTHQUAKE, :ZENHEADBUTT], :form => 0, :ability_index => 1}
	SALAMENCE = {:species => :SALAMENCE, :region => Hoenn, :moves => [:DRACOMETEOR, :HURRICANE, :FLAMETHROWER, :ROOST], :form => 0, :ability_index => 0}
	METAGROSS = {:species => :METAGROSS, :region => Hoenn, :moves => [:STEALTHROCK, :METEORMASH, :EARTHQUAKE, :TOXIC], :form => 0, :ability_index => 0}
	TORTERRA = {:species => :TORTERRA, :region => Sinnoh, :moves => [:STEALTHROCK, :WOODHAMMER, :EARTHQUAKE, :SYNTHESIS], :form => 0, :ability_index => 0}
	INFERNAPE = {:species => :INFERNAPE, :region => Sinnoh, :moves => [:NASTYPLOT, :FIREBLAST, :FOCUSBLAST, :FLAMETHROWER], :form => 0, :ability_index => 0}
	EMPOLEON = {:species => :EMPOLEON, :region => Sinnoh, :moves => [:SCALD, :FLASHCANNON, :ICEBEAM, :PROTECT], :form => 0, :ability_index => 0}
	STARAPTOR = {:species => :STARAPTOR, :region => Sinnoh, :moves => [:AERIALACE, :CLOSECOMBAT, :STEELWING, :DOUBLETEAM], :form => 0, :ability_index => 0}
	BIBAREL = {:species => :BIBAREL, :region => Sinnoh, :moves => [:WATERFALL, :BULLDOZE, :THUNDERWAVE, :YAWN], :form => 0, :ability_index => 1}
	KRICKETUNE = {:species => :KRICKETUNE, :region => Sinnoh, :moves => [:XSCISSOR, :NIGHTSLASH, :STICKYWEB, :AERIALACE], :form => 0, :ability_index => 0}
	LUXRAY = {:species => :LUXRAY, :region => Sinnoh, :moves => [:WILDCHARGE, :THUNDERFANG, :PSYCHICFANGS, :ROAR], :form => 0, :ability_index => 1}
	ROSERADE = {:species => :ROSERADE, :region => Sinnoh, :moves => [:GIGADRAIN, :TOXICSPIKES, :LEECHSEED, :GRASSYTERRAIN], :form => 0, :ability_index => 1}
	RAMPARDOS = {:species => :RAMPARDOS, :region => Sinnoh, :moves => [:ZENHEADBUTT, :STONEEDGE, :EARTHQUAKE, :AVALANCHE], :form => 0, :ability_index => 0}
	BASTIODON = {:species => :BASTIODON, :region => Sinnoh, :moves => [:IRONHEAD, :HEAVYSLAM, :STONEEDGE, :EARTHQUAKE], :form => 0, :ability_index => 0}
	WORMADAM_PLANTCLOAK = {:species => :WORMADAM, :region => Sinnoh, :moves => [:PSYCHIC, :BUGBUZZ, :PROTECT, :ENERGYBALL], :form => 0, :ability_index => 0}
	WORMADAM_SANDYCLOAK = {:species => :WORMADAM, :region => Sinnoh, :moves => [:PSYCHIC, :BUGBUZZ, :PROTECT, :EARTHPOWER], :form => 1, :ability_index => 0}
	WORMADAM_TRASHCLOAK = {:species => :WORMADAM, :region => Sinnoh, :moves => [:PSYCHIC, :BUGBUZZ, :PROTECT, :IRONHEAD], :form => 2, :ability_index => 0}
	MOTHIM = {:species => :MOTHIM, :region => Sinnoh, :moves => [:PSYCHIC, :BUGBUZZ, :PROTECT, :AIRSLASH], :form => 0, :ability_index => 0}
	VESPIQUEN = {:species => :VESPIQUEN, :region => Sinnoh, :moves => [:ATTACKORDER, :DEFENDORDER, :POWERGEM, :AIRSLASH], :form => 0, :ability_index => 0}
	PACHIRISU = {:species => :PACHIRISU, :region => Sinnoh, :moves => [:SPARK, :THUNDERWAVE, :SUPERFANG, :LASTRESORT], :form => 0, :ability_index => 0}
	FLOATZEL = {:species => :FLOATZEL, :region => Sinnoh, :moves => [:ICEFANG, :CRUNCH, :AQUATAIL, :AQUAJET], :form => 0, :ability_index => 0}
	CHERRIM = {:species => :CHERRIM, :region => Sinnoh, :moves => [:SUNNYDAY, :SOLARBEAM, :DAZZLINGGLEAM, :POLLENPUFF], :form => 0, :ability_index => 0}
	GASTRODON = {:species => :GASTRODON, :region => Sinnoh, :moves => [:MUDDYWATER, :WATERPULSE, :ANCIENTPOWER, :EARTHPOWER], :form => 0, :ability_index => 1}
	AMBIPOM = {:species => :AMBIPOM, :region => Sinnoh, :moves => [:FAKEOUT, :RETURN, :LOWKICK, :UTURN], :form => 0, :ability_index => 0}
	DRIFBLIM = {:species => :DRIFBLIM, :region => Sinnoh, :moves => [:SHADOWBALL, :CALMMIND, :SUBSTITUTE, :THUNDERBOLT], :form => 0, :ability_index => 1}
	LOPUNNY = {:species => :LOPUNNY, :region => Sinnoh, :moves => [:CLOSECOMBAT, :BOUNCE, :PLAYROUGH, :DRAINPUNCH], :form => 0, :ability_index => 0}
	MISMAGIUS = {:species => :MISMAGIUS, :region => Sinnoh, :moves => [:NASTYPLOT, :SHADOWBALL, :MYSTICALFIRE, :WILLOWISP], :form => 0, :ability_index => 0}
	HONCHKROW = {:species => :HONCHKROW, :region => Sinnoh, :moves => [:NIGHTSLASH, :SUCKERPUNCH, :AERIALACE, :STEELWING], :form => 0, :ability_index => 1}
	PURUGLY = {:species => :PURUGLY, :region => Sinnoh, :moves => [:BODYSLAM, :AERIALACE, :PLAYROUGH, :SUBSTITUTE], :form => 0, :ability_index => 0}
	SKUNTANK = {:species => :SKUNTANK, :region => Sinnoh, :moves => [:FLAMETHROWER, :THIEF, :SHADOWCLAW, :POISONJAB], :form => 0, :ability_index => 0}
	BRONZONG = {:species => :BRONZONG, :region => Sinnoh, :moves => [:STEALTHROCK, :TOXIC, :PSYWAVE, :GYROBALL], :form => 0, :ability_index => 0}
	SPIRITOMB = {:species => :SPIRITOMB, :region => Sinnoh, :moves => [:REST, :SLEEPTALK, :CALMMIND, :DARKPULSE], :form => 0, :ability_index => 0}
	GARCHOMP = {:species => :GARCHOMP, :region => Sinnoh, :moves => [:SWORDSDANCE, :EARTHQUAKE, :FIREFANG, :SCALESHOT], :form => 0, :ability_index => 0}
	LUCARIO = {:species => :LUCARIO, :region => Sinnoh, :moves => [:CLOSECOMBAT, :METEORMASH, :SWORDSDANCE, :EXTREMESPEED], :form => 0, :ability_index => 1}
	HIPPOWDON = {:species => :HIPPOWDON, :region => Sinnoh, :moves => [:EARTHQUAKE, :TOXIC, :SLACKOFF, :THUNDERFANG], :form => 0, :ability_index => 0}
	DRAPION = {:species => :DRAPION, :region => Sinnoh, :moves => [:SWORDSDANCE, :KNOCKOFF, :POISONJAB, :EARTHQUAKE], :form => 0, :ability_index => 0}
	TOXICROAK = {:species => :TOXICROAK, :region => Sinnoh, :moves => [:SWORDSDANCE, :GUNKSHOT, :DRAINPUNCH, :KNOCKOFF], :form => 0, :ability_index => 1}
	CARNIVINE = {:species => :CARNIVINE, :region => Sinnoh, :moves => [:POWERWHIP, :SEEDBOMB, :CRUNCH, :PROTECT], :form => 0, :ability_index => 0}
	LUMINEON = {:species => :LUMINEON, :region => Sinnoh, :moves => [:DEFOG, :SCALD, :UTURN, :TOXIC], :form => 0, :ability_index => 1}
	ABOMASNOW = {:species => :ABOMASNOW, :region => Sinnoh, :moves => [:SWORDSDANCE, :ICESHARD, :WOODHAMMER, :EARTHQUAKE], :form => 0, :ability_index => 0}
	WEAVILE = {:species => :WEAVILE, :region => Sinnoh, :moves => [:SWORDSDANCE, :TRIPLEAXEL, :KNOCKOFF, :ICESHARD], :form => 0, :ability_index => 0}
	MAGNEZONE = {:species => :MAGNEZONE, :region => Sinnoh, :moves => [:IRONDEFENSE, :BODYPRESS, :THUNDERBOLT, :TELEPORT], :form => 0, :ability_index => 1}
	LICKILICKY = {:species => :LICKILICKY, :region => Sinnoh, :moves => [:WISH, :PROTECT, :HEALBELL, :KNOCKOFF], :form => 0, :ability_index => 1}
	RHYPERIOR = {:species => :RHYPERIOR, :region => Sinnoh, :moves => [:EARTHQUAKE, :STONEEDGE, :STEALTHROCK, :MEGAHORN], :form => 0, :ability_index => 1}
	TANGROWTH = {:species => :TANGROWTH, :region => Sinnoh, :moves => [:POWERWHIP, :KNOCKOFF, :SLUDGEBOMB, :FOCUSBLAST], :form => 0, :ability_index => 1}
	ELECTIVIRE = {:species => :ELECTIVIRE, :region => Sinnoh, :moves => [:THUNDERBOLT, :FLAMETHROWER, :FOCUSBLAST, :VOLTSWITCH], :form => 0, :ability_index => 0}
	MAGMORTAR = {:species => :MAGMORTAR, :region => Sinnoh, :moves => [:FIREBLAST, :THUNDERBOLT, :FOCUSBLAST, :SCORCHINGSANDS], :form => 0, :ability_index => 0}
	TOGEKISS = {:species => :TOGEKISS, :region => Sinnoh, :moves => [:ANCIENTPOWER, :AIRSLASH, :DAZZLINGGLEAM, :AURASPHERE], :form => 0, :ability_index => 1}
	YANMEGA = {:species => :YANMEGA, :region => Sinnoh, :moves => [:BUGBUZZ, :AIRSLASH, :UTURN, :GIGADRAIN], :form => 0, :ability_index => 0}
	LEAFEON = {:species => :LEAFEON, :region => Sinnoh, :moves => [:SWORDSDANCE, :LEAFBLADE, :KNOCKOFF, :SYNTHESIS], :form => 0, :ability_index => 0}
	GLACEON = {:species => :GLACEON, :region => Sinnoh, :moves => [:ICEBEAM, :FREEZEDRY, :SHADOWBALL, :WATERPULSE], :form => 0, :ability_index => 0}
	GLISCOR = {:species => :GLISCOR, :region => Sinnoh, :moves => [:EARTHQUAKE, :SWORDSDANCE, :XSCISSOR, :POISONJAB], :form => 0, :ability_index => 0}
	MAMOSWINE = {:species => :MAMOSWINE, :region => Sinnoh, :moves => [:ICICLECRASH, :EARTHQUAKE, :ICESHARD, :KNOCKOFF], :form => 0, :ability_index => 0}
	PORYGONZ = {:species => :PORYGONZ, :region => Sinnoh, :moves => [:TRIATTACK, :SHADOWBALL, :TRICK, :THUNDERBOLT], :form => 0, :ability_index => 0}
	GALLADE = {:species => :GALLADE, :region => Sinnoh, :moves => [:SWORDSDANCE, :CLOSECOMBAT, :ZENHEADBUTT, :KNOCKOFF], :form => 0, :ability_index => 0}
	PROBOPASS = {:species => :PROBOPASS, :region => Sinnoh, :moves => [:POWERGEM, :DISCHARGE, :EARTHPOWER, :THUNDERWAVE], :form => 0, :ability_index => 0}
	DUSKNOIR = {:species => :DUSKNOIR, :region => Sinnoh, :moves => [:POLTERGEIST, :EARTHQUAKE, :SHADOWSNEAK, :POWERUPPUNCH], :form => 0, :ability_index => 0}
	FROSLASS = {:species => :FROSLASS, :region => Sinnoh, :moves => [:HAIL, :SHADOWBALL, :FROSTBREATH, :WILLOWISP], :form => 0, :ability_index => 0}
	ROTOM = {:species => :ROTOM, :region => Sinnoh, :moves => [:VOLTSWITCH, :SHADOWBALL, :WILLOWISP, :THUNDERBOLT], :form => 0, :ability_index => 0}
	ROTOM_HEAT = {:species => :ROTOM, :region => Sinnoh, :moves => [:OVERHEAT, :VOLTSWITCH, :TOXIC, :PAINSPLIT], :form => 1, :ability_index => 0}
	ROTOM_WASH = {:species => :ROTOM, :region => Sinnoh, :moves => [:VOLTSWITCH, :HYDROPUMP, :PAINSPLIT, :WILLOWISP], :form => 2, :ability_index => 0}
	ROTOM_FROST = {:species => :ROTOM, :region => Sinnoh, :moves => [:NASTYPLOT, :BLIZZARD, :THUNDERBOLT, :PAINSPLIT], :form => 3, :ability_index => 0}
	ROTOM_FAN = {:species => :ROTOM, :region => Sinnoh, :moves => [:NASTYPLOT, :THUNDERBOLT, :AIRSLASH, :PAINSPLIT], :form => 4, :ability_index => 0}
	ROTOM_MOW = {:species => :ROTOM, :region => Sinnoh, :moves => [:NASTYPLOT, :LEAFSTORM, :VOLTSWITCH, :PAINSPLIT], :form => 5, :ability_index => 0}
	SERPERIOR = {:species => :SERPERIOR, :region => Unova, :moves => [:LEAFSTORM, :SUBSTITUTE, :GLARE, :TOXIC], :form => 0, :ability_index => 0}
	EMBOAR = {:species => :EMBOAR, :region => Unova, :moves => [:HAMMERARM, :FLAREBLITZ, :ASSURANCE, :STONEEDGE], :form => 0, :ability_index => 0}
	SAMUROTT = {:species => :SAMUROTT, :region => Unova, :moves => [:AQUATAIL, :SWORDSDANCE, :AQUAJET, :DRAGONTAIL], :form => 0, :ability_index => 0}
	WATCHOG = {:species => :WATCHOG, :region => Unova, :moves => [:HYPERFANG, :HYPNOSIS, :NASTYPLOT, :BATONPASS], :form => 0, :ability_index => 1}
	STOUTLAND = {:species => :STOUTLAND, :region => Unova, :moves => [:PLAYROUGH, :DIG, :IRONHEAD, :CRUNCH], :form => 0, :ability_index => 0}
	LIEPARD = {:species => :LIEPARD, :region => Unova, :moves => [:NIGHTSLASH, :SUCKERPUNCH, :PLAYROUGH, :SHADOWCLAW], :form => 0, :ability_index => 1}
	SIMISAGE = {:species => :SIMISAGE, :region => Unova, :moves => [:SEEDBOMB, :BRICKBREAK, :ROCKSLIDE, :GUNKSHOT], :form => 0, :ability_index => 0}
	SIMISEAR = {:species => :SIMISEAR, :region => Unova, :moves => [:WILLOWISP, :FLAMETHROWER, :ACROBATICS, :SHADOWCLAW], :form => 0, :ability_index => 0}
	SIMIPOUR = {:species => :SIMIPOUR, :region => Unova, :moves => [:NASTYPLOT, :SURF, :ICEBEAM, :GRASSKNOT], :form => 0, :ability_index => 0}
	MUSHARNA = {:species => :MUSHARNA, :region => Unova, :moves => [:FUTURESIGHT, :MOONBLAST, :MOONLIGHT, :HYPNOSIS], :form => 0, :ability_index => 1}
	UNFEZANT = {:species => :UNFEZANT, :region => Unova, :moves => [:SKYATTACK, :GIGAIMPACT, :BRAVEBIRD, :REST], :form => 0, :ability_index => 1}
	ZEBSTRIKA = {:species => :ZEBSTRIKA, :region => Unova, :moves => [:THUNDERBOLT, :VOLTSWITCH, :OVERHEAT, :HIDDENPOWER], :form => 0, :ability_index => 1}
	GIGALITH = {:species => :GIGALITH, :region => Unova, :moves => [:STEALTHROCK, :STONEEDGE, :EARTHQUAKE, :TOXIC], :form => 0, :ability_index => 1}
	SWOOBAT = {:species => :SWOOBAT, :region => Unova, :moves => [:PSYCHIC, :AIRSLASH, :STOREDPOWER, :HEATWAVE], :form => 0, :ability_index => 1}
	EXCADRILL = {:species => :EXCADRILL, :region => Unova, :moves => [:EARTHQUAKE, :IRONHEAD, :RAPIDSPIN, :TOXIC], :form => 0, :ability_index => 0}
	AUDINO = {:species => :AUDINO, :region => Unova, :moves => [:WISH, :PROTECT, :KNOCKOFF, :ENCORE], :form => 0, :ability_index => 0}
	CONKELDURR = {:species => :CONKELDURR, :region => Unova, :moves => [:DRAINPUNCH, :FACADE, :KNOCKOFF, :MACHPUNCH], :form => 0, :ability_index => 0}
	SEISMITOAD = {:species => :SEISMITOAD, :region => Unova, :moves => [:DRAINPUNCH, :LIQUIDATION, :ROCKSLIDE, :SUPERSONIC], :form => 0, :ability_index => 1}
	THROH = {:species => :THROH, :region => Unova, :moves => [:SUPERPOWER, :EARTHQUAKE, :KNOCKOFF, :POISONJAB], :form => 0, :ability_index => 0}
	SAWK = {:species => :SAWK, :region => Unova, :moves => [:CLOSECOMBAT, :KNOCKOFF, :POISONJAB, :EARTHQUAKE], :form => 0, :ability_index => 0}
	LEAVANNY = {:species => :LEAVANNY, :region => Unova, :moves => [:STICKYWEB, :LEAFBLADE, :XSCISSOR, :MAGICCOAT], :form => 0, :ability_index => 1}
	SCOLIPEDE = {:species => :SCOLIPEDE, :region => Unova, :moves => [:MEGAHORN, :TOXIC, :CROSSPOISON, :XSCISSOR], :form => 0, :ability_index => 1}
	WHIMSICOTT = {:species => :WHIMSICOTT, :region => Unova, :moves => [:MOONBLAST, :SUNNYDAY, :SOLARBEAM, :ENERGYBALL], :form => 0, :ability_index => 1}
	LILLIGANT = {:species => :LILLIGANT, :region => Unova, :moves => [:ENERGYBALL, :SYNTHESIS, :PETALDANCE, :QUIVERDANCE], :form => 0, :ability_index => 1}
	KROOKODILE = {:species => :KROOKODILE, :region => Unova, :moves => [:EARTHQUAKE, :KNOCKOFF, :STEALTHROCK, :TAUNT], :form => 0, :ability_index => 1}
	DARMANITAN = {:species => :DARMANITAN, :region => Unova, :moves => [:FLAREBLITZ, :UTURN, :ROCKSLIDE, :EARTHQUAKE], :form => 0, :ability_index => 0}
	DARMANITAN_GALAR = {:species => :DARMANITAN, :region => Galar, :moves => [:UTURN, :ICICLECRASH, :FLAREBLITZ, :ROCKSLIDE], :form => 2, :ability_index => 0}
	MARACTUS = {:species => :MARACTUS, :region => Unova, :moves => [:SPIKES, :ENDEAVOR, :ENERGYBALL, :SUCKERPUNCH], :form => 0, :ability_index => 1}
	CRUSTLE = {:species => :CRUSTLE, :region => Unova, :moves => [:XSCISSOR, :STEALTHROCK, :SHELLSMASH, :ROCKSLIDE], :form => 0, :ability_index => 1}
	SCRAFTY = {:species => :SCRAFTY, :region => Unova, :moves => [:DRAGONDANCE, :CLOSECOMBAT, :KNOCKOFF, :IRONHEAD], :form => 0, :ability_index => 1}
	SIGILYPH = {:species => :SIGILYPH, :region => Unova, :moves => [:CALMMIND, :AIRSLASH, :ROOST, :PSYCHICH], :form => 0, :ability_index => 0}
	COFAGRIGUS = {:species => :COFAGRIGUS, :region => Unova, :moves => [:IRONDEFENSE, :BODYPRESS, :SHADOWBALL, :REST], :form => 0, :ability_index => 0}
	CARRACOSTA = {:species => :CARRACOSTA, :region => Unova, :moves => [:SHELLSMASH, :STONEEDGE, :AQUAJET, :LIQUIDATION], :form => 0, :ability_index => 1}
	ARCHEOPS = {:species => :ARCHEOPS, :region => Unova, :moves => [:STONEEDGE, :EARTHQUAKE, :DUALWINGBEAT, :ROOST], :form => 0, :ability_index => 0}
	GARBODOR = {:species => :GARBODOR, :region => Unova, :moves => [:GUNKSHOT, :SPIKES, :STOMPINGTANTRUM, :PAINSPLIT], :form => 0, :ability_index => 0}
	ZOROARK = {:species => :ZOROARK, :region => Unova, :moves => [:DARKPULSE, :FLAMETHROWER, :SLUDGEBOMB, :UTURN], :form => 0, :ability_index => 0}
	CINCCINO = {:species => :CINCCINO, :region => Unova, :moves => [:TAILSLAP, :TRIPLEAXEL, :BULLETSEED, :KNOCKOFF], :form => 0, :ability_index => 1}
	GOTHITELLE = {:species => :GOTHITELLE, :region => Unova, :moves => [:PSYCHIC, :CHARM, :SHADOWBALL, :THUNDERBOLT], :form => 0, :ability_index => 0}
	REUNICLUS = {:species => :REUNICLUS, :region => Unova, :moves => [:CALMMIND, :PSYSHOCK, :FOCUSBLAST, :RECOVER], :form => 0, :ability_index => 0}
	SWANNA = {:species => :SWANNA, :region => Unova, :moves => [:AERIALACE, :HURRICANE, :WATERPULSE, :ICEBEAM], :form => 0, :ability_index => 0}
	VANILLUXE = {:species => :VANILLUXE, :region => Unova, :moves => [:BLIZZARD, :FREEZEDRY, :ICESHARD, :TAUNT], :form => 0, :ability_index => 1}
	SAWSBUCK = {:species => :SAWSBUCK, :region => Unova, :moves => [:MEGAHORN, :HORNLEECH, :JUMPKICK, :LEECHSEED], :form => 0, :ability_index => 0}
	EMOLGA = {:species => :EMOLGA, :region => Unova, :moves => [:THUNDERBOLT, :UTURN, :ENCORE, :ROOST], :form => 0, :ability_index => 0}
	ESCAVALIER = {:species => :ESCAVALIER, :region => Unova, :moves => [:IRONHEAD, :SWORDSDANCE, :XSCISSOR, :BRUTALSWING], :form => 0, :ability_index => 1}
	AMOONGUSS = {:species => :AMOONGUSS, :region => Unova, :moves => [:GIGADRAIN, :SLUDGEBOMB, :FOULPLAY, :SPORE], :form => 0, :ability_index => 0}
	JELLICENT = {:species => :JELLICENT, :region => Unova, :moves => [:WATERSPOUT, :SHADOWBALL, :TRICK, :SURF], :form => 0, :ability_index => 0}
	ALOMOMOLA = {:species => :ALOMOMOLA, :region => Unova, :moves => [:SCALD, :WISH, :PROTECT, :RAINDANCE], :form => 0, :ability_index => 1}
	GALVANTULA = {:species => :GALVANTULA, :region => Unova, :moves => [:BUGBUZZ, :ELECTROBALL, :DISCHARGE, :STICKYWEB], :form => 0, :ability_index => 0}
	FERROTHORN = {:species => :FERROTHORN, :region => Unova, :moves => [:SPIKES, :KNOCKOFF, :LEECHSEED, :POWERWHIP], :form => 0, :ability_index => 1}
	KLINKLANG = {:species => :KLINKLANG, :region => Unova, :moves => [:SHIFTGEAR, :GEARGRIND, :WILDCHARGE, :SUBSTITUTE], :form => 0, :ability_index => 0}
	EELEKTROSS = {:species => :EELEKTROSS, :region => Unova, :moves => [:VOLTSWITCH, :GIGADRAIN, :FLAMETHROWER, :DRAINPUNCH], :form => 0, :ability_index => 0}
	BEHEEYEM = {:species => :BEHEEYEM, :region => Unova, :moves => [:PSYCHIC, :THUNDERBOLT, :RECOVER, :NASTYPLOT], :form => 0, :ability_index => 1}
	CHANDELURE = {:species => :CHANDELURE, :region => Unova, :moves => [:FIREBLAST, :SHADOWBALL, :TOXIC, :ENERGYBALL], :form => 0, :ability_index => 1}
	HAXORUS = {:species => :HAXORUS, :region => Unova, :moves => [:SWORDSDANCE, :OUTRAGE, :EARTHQUAKE, :POISONJAB], :form => 0, :ability_index => 0}
	BEARTIC = {:species => :BEARTIC, :region => Unova, :moves => [:HAIL, :SWORDSDANCE, :ICICLECRASH, :SUPERPOWER], :form => 0, :ability_index => 0}
	CRYOGONAL = {:species => :CRYOGONAL, :region => Unova, :moves => [:RAPIDSPIN, :RECOVER, :FREEZEDRY, :KNOCKOFF], :form => 0, :ability_index => 0}
	ACCELGOR = {:species => :ACCELGOR, :region => Unova, :moves => [:BUGBUZZ, :TOXIC, :WATERSHURIKEN, :GIGADRAIN], :form => 0, :ability_index => 1}
	STUNFISK = {:species => :STUNFISK, :region => Unova, :moves => [:STEALTHROCK, :DISCHARGE, :EARTHPOWER, :REST], :form => 0, :ability_index => 1}
	STUNFISK_GALAR = {:species => :STUNFISK, :region => Galar, :moves => [:STEALTHROCK, :EARTHQUAKE, :YAWN, :METALCLAW], :form => 1, :ability_index => 0}
	MIENSHAO = {:species => :MIENSHAO, :region => Unova, :moves => [:HIGHJUMPKICK, :KNOCKOFF, :UTURN, :FAKEOUT], :form => 0, :ability_index => 1}
	DRUDDIGON = {:species => :DRUDDIGON, :region => Unova, :moves => [:DRAGONTAIL, :EARTHQUAKE, :GLARE, :TAUNT], :form => 0, :ability_index => 1}
	GOLURK = {:species => :GOLURK, :region => Unova, :moves => [:STEALTHROCK, :EARTHQUAKE, :SHADOWPUNCH, :ICEPUNCH], :form => 0, :ability_index => 0}
	BISHARP = {:species => :BISHARP, :region => Unova, :moves => [:IRONHEAD, :KNOCKOFF, :SUCKERPUNCH, :SWORDSDANCE], :form => 0, :ability_index => 0}
	BOUFFALANT = {:species => :BOUFFALANT, :region => Unova, :moves => [:SUBSTITUTE, :SWORDSDANCE, :BODYSLAM, :THROATCHOP], :form => 0, :ability_index => 1}
	BRAVIARY = {:species => :BRAVIARY, :region => Unova, :moves => [:SUBSTITUTE, :BULKUP, :BRAVEBIRD, :ROOST], :form => 0, :ability_index => 0}
	MANDIBUZZ = {:species => :MANDIBUZZ, :region => Unova, :moves => [:FOULPLAY, :DEFOG, :UTURN, :ROOST], :form => 0, :ability_index => 1}
	HEATMOR = {:species => :HEATMOR, :region => Unova, :moves => [:FIREBLAST, :GIGADRAIN, :FOCUSBLAST, :SCORCHINGSANDS], :form => 0, :ability_index => 0}
	DURANT = {:species => :DURANT, :region => Unova, :moves => [:FIRSTIMPRESSION, :SUPERPOWER, :ROCKSLIDE, :IRONHEAD], :form => 0, :ability_index => 0}
	HYDREIGON = {:species => :HYDREIGON, :region => Unova, :moves => [:DRACOMETEOR, :DARKPULSE, :FLAMETHROWER, :ROOST], :form => 0, :ability_index => 1}
	VOLCARONA = {:species => :VOLCARONA, :region => Unova, :moves => [:QUIVERDANCE, :FLAMETHROWER, :BUGBUZZ, :PSYCHIC], :form => 0, :ability_index => 0}
	CHESNAUGHT = {:species => :CHESNAUGHT, :region => Kalos, :moves => [:WOODHAMMER, :DRAINPUNCH, :SYNTHESIS, :SPIKEYSHIELD], :form => 0, :ability_index => 0}
	DELPHOX = {:species => :DELPHOX, :region => Kalos, :moves => [:CALMMIND, :FIREBLAST, :PSYCHIC, :GRASSKNOT], :form => 0, :ability_index => 0}
	GRENINJA = {:species => :GRENINJA, :region => Kalos, :moves => [:HYDROPUMP, :DARKPULSE, :WATERSHURIKEN, :SPIKES], :form => 0, :ability_index => 0}
	DIGGERSBY = {:species => :DIGGERSBY, :region => Kalos, :moves => [:EARTHQUAKE, :HAMMERARM, :SWORDSDANCE, :BOUNCE], :form => 0, :ability_index => 0}
	TALONFLAME = {:species => :TALONFLAME, :region => Kalos, :moves => [:AERIALACE, :FLAMECHARGE, :ACROBATICS, :FLAREBLITZ], :form => 0, :ability_index => 0}
	VIVILLON = {:species => :VIVILLON, :region => Kalos, :moves => [:DRAININGKISS, :LIGHTSCREEN, :SUPERSONIC, :BUGBUZZ], :form => 0, :ability_index => 0}
	PYROAR = {:species => :PYROAR, :region => Kalos, :moves => [:FLAMETHROWER, :HYPERVOICE, :DARKPULSE, :WILLOWISP], :form => 0, :ability_index => 0}
	FLORGES = {:species => :FLORGES, :region => Kalos, :moves => [:MISTYTERRAIN, :MOONBLAST, :GRASSKNOT, :HIDDENPOWER], :form => 0, :ability_index => 0}
	GOGOAT = {:species => :GOGOAT, :region => Kalos, :moves => [:BULKUP, :HORNLEECH, :EARTHQUAKE, :ROCKSLIDE], :form => 0, :ability_index => 0}
	PANGORO = {:species => :PANGORO, :region => Kalos, :moves => [:KNOCKOFF, :CLOSECOMBAT, :IRONHEAD, :DRAINPUNCH], :form => 0, :ability_index => 0}
	FURFROU = {:species => :FURFROU, :region => Kalos, :moves => [:UTURN, :THUNDERWAVE, :SUCKERPUNCH, :CHARM], :form => 0, :ability_index => 0}
	MEOWSTIC = {:species => :MEOWSTIC, :region => Kalos, :moves => [:REFLECT, :LIGHTSCREEN, :THUNDERWAVE, :PSYCHIC], :form => 0, :ability_index => 0}
	AEGISLASH = {:species => :AEGISLASH, :region => Kalos, :moves => [:SHADOWBALL, :FLASHCANNON, :CLOSECOMBAT, :KINGSSHIELD], :form => 0, :ability_index => 0}
	AROMATISSE = {:species => :AROMATISSE, :region => Kalos, :moves => [:MOONBLAST, :WISH, :PROTECT, :HEALBELL], :form => 0, :ability_index => 0}
	SLURPUFF = {:species => :SLURPUFF, :region => Kalos, :moves => [:STICKYWEB, :MAGICCOAT, :MOONBLAST, :YAWN], :form => 0, :ability_index => 0}
	MALAMAR = {:species => :MALAMAR, :region => Kalos, :moves => [:SUPERPOWER, :KNOCKOFF, :REST, :SLEEPTALK], :form => 0, :ability_index => 0}
	BARBARACLE = {:species => :BARBARACLE, :region => Kalos, :moves => [:SHELLSMASH, :LIQUIDATION, :STONEEDGE, :GRASSKNOT], :form => 0, :ability_index => 0}
	DRAGALGE = {:species => :DRAGALGE, :region => Kalos, :moves => [:DRACOMETEOR, :SLUDGEBOMB, :FLIPTURN, :SCALD], :form => 0, :ability_index => 0}
	CLAWITZER = {:species => :CLAWITZER, :region => Kalos, :moves => [:WATERPULSE, :ICEBEAM, :DARKPULSE, :AURASPHERE], :form => 0, :ability_index => 0}
	HELIOLISK = {:species => :HELIOLISK, :region => Kalos, :moves => [:THUNDERBOLT, :HYPERVOICE, :VOLTSWITCH, :DARKPULSE], :form => 0, :ability_index => 0}
	TYRANTRUM = {:species => :TYRANTRUM, :region => Kalos, :moves => [:HEADSMASH, :OUTRAGE, :CLOSECOMBAT, :DRAGONCLAW], :form => 0, :ability_index => 0}
	AURORUS = {:species => :AURORUS, :region => Kalos, :moves => [:ICEBEAM, :ANCIENTPOWER, :EARTHPOWER, :BLIZZARD], :form => 0, :ability_index => 0}
	SYLVEON = {:species => :SYLVEON, :region => Kalos, :moves => [:MOONBLAST, :PSYSHOCK, :MISTYTERRAIN, :MYSTICALFIRE], :form => 0, :ability_index => 0}
	HAWLUCHA = {:species => :HAWLUCHA, :region => Kalos, :moves => [:FLYINGPRESS, :SUBMISSION, :ROCKTOMB, :POISONJAB], :form => 0, :ability_index => 1}
	DEDENNE = {:species => :DEDENNE, :region => Kalos, :moves => [:THUNDER, :PARABOLICCHARGE, :DAZZLINGGLEAM, :ELECTROWEB], :form => 0, :ability_index => 0}
	CARBINK = {:species => :CARBINK, :region => Kalos, :moves => [:STEALTHROCK, :MOONBLAST, :PROTECT, :BODYPRESS], :form => 0, :ability_index => 0}
	GOODRA = {:species => :GOODRA, :region => Kalos, :moves => [:DRACOMETEOR, :THUNDERBOLT, :FIREBLAST, :EARTHQUAKE], :form => 0, :ability_index => 0}
	KLEFKI = {:species => :KLEFKI, :region => Kalos, :moves => [:SPIKES, :DAZZLINGGLEAM, :THUNDERWAVE, :TOXIC], :form => 0, :ability_index => 0}
	TREVENANT = {:species => :TREVENANT, :region => Kalos, :moves => [:POLTERGEIST, :WOODHAMMER, :HORNLEECH, :EARTHQUAKE], :form => 0, :ability_index => 0}
	GOURGEIST = {:species => :GOURGEIST, :region => Kalos, :moves => [:POWERWHIP, :POLTERGEIST, :SHADOWSNEAK, :FIREBLAST], :form => 0, :ability_index => 1}
	AVALUGG = {:species => :AVALUGG, :region => Kalos, :moves => [:AVALANCHE, :HAIL, :EARTHQUAKE, :STONEEDGE], :form => 0, :ability_index => 1}
	NOIVERN = {:species => :NOIVERN, :region => Kalos, :moves => [:DRACOMETEOR, :FLAMETHROWER, :ROOST, :UTURN], :form => 0, :ability_index => 1}
	DECIDUEYE = {:species => :DECIDUEYE, :region => Alola, :moves => [:POLTERGEIST, :LEAFBLADE, :UTURN, :SHADOWSNEAK], :form => 0, :ability_index => 0}
	INCINEROAR = {:species => :INCINEROAR, :region => Alola, :moves => [:DARKESTLARIAT, :OVERHEAT, :SWORDSDANCE, :BRICKBREAK], :form => 0, :ability_index => 0}
	PRIMARINA = {:species => :PRIMARINA, :region => Alola, :moves => [:SPARKLINGARIA, :MOONBLAST, :MISTYTERRAIN, :REFLECT], :form => 0, :ability_index => 0}
	TOUCANNON = {:species => :TOUCANNON, :region => Alola, :moves => [:BEAKBLAST, :ROCKBLAST, :BULLETSEED, :PLUCK], :form => 0, :ability_index => 1}
	GUMSHOOS = {:species => :GUMSHOOS, :region => Alola, :moves => [:HYPERFANG, :CRUNCH, :BULLDOZE, :SUBSTITUTE], :form => 0, :ability_index => 1}
	VIKAVOLT = {:species => :VIKAVOLT, :region => Alola, :moves => [:ZAPCANNON, :THUNDERBOLT, :BUGBUZZ, :FLASHCANNON], :form => 0, :ability_index => 0}
	CRABOMINABLE = {:species => :CRABOMINABLE, :region => Alola, :moves => [:DRAINPUNCH, :ICEHAMMER, :EARTHQUAKE, :THUNDERPUNCH], :form => 0, :ability_index => 1}
	RIBOMBEE = {:species => :RIBOMBEE, :region => Alola, :moves => [:POLLENPUFF, :MOONBLAST, :QUIVERDANCE, :STICKYWEB], :form => 0, :ability_index => 1}
	WISHIWASHI = {:species => :WISHIWASHI, :region => Alola, :moves => [:LIQUIDATION, :EARTHQUAKE, :ICEBEAM, :ENDURE], :form => 0, :ability_index => 0}
	LYCANROC_MIDDAY = {:species => :LYCANROC, :region => Alola, :moves => [:ACCELEROCK, :STONEEDGE, :CRUNCH, :THUNDERFANG], :form => 0, :ability_index => 0}
	LYCANROC_MIDNIGHT = {:species => :LYCANROC, :region => Alola, :moves => [:SWORDSDANCE, :STONEEDGE, :CLOSECOMBAT, :SUCKERPUNCH], :form => 1, :ability_index => 0}
	LYCANROC_DUSK = {:species => :LYCANROC, :region => Alola, :moves => [:STONEEDGE, :STEALTHROCK, :ROCKSLIDE, :CRUNCH], :form => 2, :ability_index => 0}
	TOXAPEX = {:species => :TOXAPEX, :region => Alola, :moves => [:TOXIC, :TOXICSPIKES, :RECOVER, :SCALD], :form => 0, :ability_index => 0}
	MUDSDALE = {:species => :MUDSDALE, :region => Alola, :moves => [:STEALTHROCK, :EARTHQUAKE, :BODYPRESS, :SMACKDOWN], :form => 0, :ability_index => 1}
	ARAQUANID = {:species => :ARAQUANID, :region => Alola, :moves => [:LEECHLIFE, :LIQUIDATION, :CRUNCH, :RAINDANCE], :form => 0, :ability_index => 0}
	LURANTIS = {:species => :LURANTIS, :region => Alola, :moves => [:LEAFSTORM, :SUPERPOWER, :SYNTHESIS, :SUNNYDAY], :form => 0, :ability_index => 0}
	SHIINOTIC = {:species => :SHIINOTIC, :region => Alola, :moves => [:SPORE, :STRENGTHSAP, :GIGADRAIN, :MOONBLAST], :form => 0, :ability_index => 1}
	SALAZZLE = {:species => :SALAZZLE, :region => Alola, :moves => [:TOXIC, :SLUDGEWAVE, :FLAMETHROWER, :DRAGONPULSE], :form => 0, :ability_index => 0}
	BEWEAR = {:species => :BEWEAR, :region => Alola, :moves => [:SWORDSDANCE, :DOUBLEEDGE, :DRAINPUNCH, :DARKESTLARIAT], :form => 0, :ability_index => 0}
	TSAREENA = {:species => :TSAREENA, :region => Alola, :moves => [:TROPKICK, :POWERWHIP, :HIGHJUMPKICK, :UURN], :form => 0, :ability_index => 1}
	COMFEY = {:species => :COMFEY, :region => Alola, :moves => [:SYNTHESIS, :DAZZLINGGLEAM, :LEECHSEED, :CALMMIND], :form => 0, :ability_index => 1}
	ORANGURU = {:species => :ORANGURU, :region => Alola, :moves => [:PSYCHIC, :THUNDERBOLT, :NASTYPLOT, :TRICKROOM], :form => 0, :ability_index => 0}
	PASSIMIAN = {:species => :PASSIMIAN, :region => Alola, :moves => [:CLOSECOMBAT, :KNOCKOFF, :GUNKSHOT, :ROCKSLIDE], :form => 0, :ability_index => 0}
	GOLISOPOD = {:species => :GOLISOPOD, :region => Alola, :moves => [:LIQUIDATION, :FIRSTIMPRESSION, :SUCKERPUNCH, :XSCISSOR], :form => 0, :ability_index => 0}
	PALOSSAND = {:species => :PALOSSAND, :region => Alola, :moves => [:EARTHPOWER, :SHADOWBALL, :SHOREUP, :STEALTHROCK], :form => 0, :ability_index => 0}
	PYUKUMUKU = {:species => :PYUKUMUKU, :region => Alola, :moves => [:COUNTER, :TOXIC, :PROTECT, :SOAK], :form => 0, :ability_index => 0}
	SILVALLY = {:species => :SILVALLY, :region => Alola, :moves => [:MULTIATTACK, :CRUNCH, :FLAMETHROWER, :SURF], :form => 0, :ability_index => 0}
	ORICORIO_BAILE = {:species => :ORICORIO, :region => Alola, :moves => [:CALMMIND, :HURRICANE, :REVELATIONDANCE, :ROOST], :form => 0, :ability_index => 0}
	ORICORIO_POMPOM = {:species => :ORICORIO, :region => Alola, :moves => [:CALMMIND, :HURRICANE, :REVELATIONDANCE, :ROOST], :form => 1, :ability_index => 0}
	ORICORIO_PAU = {:species => :ORICORIO, :region => Alola, :moves => [:CALMMIND, :HURRICANE, :REVELATIONDANCE, :ROOST], :form => 2, :ability_index => 0}
	ORICORIO_SENSU = {:species => :ORICORIO, :region => Alola, :moves => [:CALMMIND, :HURRICANE, :REVELATIONDANCE, :ROOST], :form => 3, :ability_index => 0}
	MINIOR = {:species => :MINIOR, :region => Alola, :moves => [:SHELLSMASH, :STONEEDGE, :EARTHQUAKE, :ACROBATICS], :form => 0, :ability_index => 0}
	KOMALA = {:species => :KOMALA, :region => Alola, :moves => [:WOODHAMMER, :THRASH, :ROLLOUT, :RAPIDSPIN], :form => 0, :ability_index => 0}
	TURTONATOR = {:species => :TURTONATOR, :region => Alola, :moves => [:SHELLSMASH, :FIREBLAST, :DRACOMETEOR, :DRAGONPULSE], :form => 0, :ability_index => 0}
	TOGEDEMARU = {:species => :TOGEDEMARU, :region => Alola, :moves => [:ZINGZAP, :IRONHEAD, :NUZZLE, :UTURN], :form => 0, :ability_index => 1}
	MIMIKYU = {:species => :MIMIKYU, :region => Alola, :moves => [:SWORDSDANCE, :PLAYROUGH, :SHADOWSNEAK, :SHADOWCLAW], :form => 0, :ability_index => 0}
	BRUXISH = {:species => :BRUXISH, :region => Alola, :moves => [:SWORDSDANCE, :PSYCHICFANGS, :AQUAJET, :CRUNCH], :form => 0, :ability_index => 1}
	DRAMPA = {:species => :DRAMPA, :region => Alola, :moves => [:HYPERVOICE, :DRACOMETEOR, :FLAMETHROWER, :ENERGYBALL], :form => 0, :ability_index => 1}
	DHELMISE = {:species => :DHELMISE, :region => Alola, :moves => [:ANCHORSHOT, :POWERWHIP, :POLTERGEIST, :SYNTHESIS], :form => 0, :ability_index => 0}
	KOMMOO = {:species => :KOMMOO, :region => Alola, :moves => [:BODYPRESS, :EARTHQUAKE, :FLAMETHROWER, :CLANGINGSCALES], :form => 0, :ability_index => 0}
	RILLABOOM = {:species => :RILLABOOM, :region => Galar, :moves => [:SWORDSDANCE, :DRUMBEATING, :EARTHQUAKE, :SUPERPOWER], :form => 0, :ability_index => 0}
	CINDERACE = {:species => :CINDERACE, :region => Galar, :moves => [:PYROBALL, :COURTCHANGE, :ZENHEADBUTT, :GUNKSHOT], :form => 0, :ability_index => 0}
	INTELEON = {:species => :INTELEON, :region => Galar, :moves => [:SNIPESHOT, :ICEBEAM, :AIRSLASH, :AQUARING], :form => 0, :ability_index => 0}
	GREEDENT = {:species => :GREEDENT, :region => Galar, :moves => [:STUFFCHEEKS, :STOCKPILE, :SPITUP, :BELCH], :form => 0, :ability_index => 0}
	CORVIKNIGHT = {:species => :CORVIKNIGHT, :region => Galar, :moves => [:IRONHEAD, :DRILLPECK, :PROTECT, :BODYPRESS], :form => 0, :ability_index => 0}
	ORBEETLE = {:species => :ORBEETLE, :region => Galar, :moves => [:PSYCHIC, :BUGBUZZ, :REFLECT, :LIGHTSCREEN], :form => 0, :ability_index => 0}
	THIEVUL = {:species => :THIEVUL, :region => Galar, :moves => [:NIGHTSLASH, :FOULPLAY, :PLAYROUGH, :DIG], :form => 0, :ability_index => 1}
	ELDEGOSS = {:species => :ELDEGOSS, :region => Galar, :moves => [:LEAFSTORM, :LEAFTORNADO, :POLLENPUFF, :SING], :form => 0, :ability_index => 0}
	DUBWOOL = {:species => :DUBWOOL, :region => Galar, :moves => [:COTTONGUARD, :BODYPRESS, :REST, :PAYBACK], :form => 0, :ability_index => 0}
	DREDNAW = {:species => :DREDNAW, :region => Galar, :moves => [:LIQUIDATION, :ROCKTOMB, :JAWLOCK, :CRUNCH], :form => 0, :ability_index => 0}
	BOLTUND = {:species => :BOLTUND, :region => Galar, :moves => [:THUNDERFANG, :FIREFANG, :PLAYROUGH, :PSYCHICFANGS], :form => 0, :ability_index => 0}
	COALOSSAL = {:species => :COALOSSAL, :region => Galar, :moves => [:ANCIENTPOWER, :HEATCRASH, :BURNUP, :ROCKBLAST], :form => 0, :ability_index => 0}
	FLAPPLE = {:species => :FLAPPLE, :region => Galar, :moves => [:GRAVAPPLE, :OUTRAGE, :GRASSYGLIDE, :SUCKERPUNCH], :form => 0, :ability_index => 0}
	APPLETUN = {:species => :APPLETUN, :region => Galar, :moves => [:DRACOMETEOR, :APPLEACID, :DRAGONPULSE, :GIGADRAIN], :form => 0, :ability_index => 0}
	SANDACONDA = {:species => :SANDACONDA, :region => Galar, :moves => [:STEALTHROCK, :EARTHQUAKE, :GLARE, :REST], :form => 0, :ability_index => 1}
	CRAMORANT = {:species => :CRAMORANT, :region => Galar, :moves => [:ROOST, :SURF, :HURRICANE, :SUBSTITUTE], :form => 0, :ability_index => 0}
	BARRASKEWDA = {:species => :BARRASKEWDA, :region => Galar, :moves => [:LIQUIDATION, :CLOSECOMBAT, :FLIPTURN, :PSYCHICFANGS], :form => 0, :ability_index => 0}
	TOXTRICITY = {:species => :TOXTRICITY, :region => Galar, :moves => [:BOOMBURST, :OVERDRIVE, :SNARL, :SLUDGEWAVE], :form => 0, :ability_index => 0}
	CENTISKORCH = {:species => :CENTISKORCH, :region => Galar, :moves => [:FIRELASH, :LUNGE, :CRUNCH, :POWERWHIP], :form => 0, :ability_index => 1}
	GRAPPLOCT = {:species => :GRAPPLOCT, :region => Galar, :moves => [:BULKUP, :DRAINPUNCH, :BRUTALSWING, :SUCKERPUNCH], :form => 0, :ability_index => 0}
	POLTEAGEIST = {:species => :POLTEAGEIST, :region => Galar, :moves => [:SHELLSMASH, :SHADOWBALL, :GIGADRAIN, :POLTERGEIST], :form => 0, :ability_index => 0}
	HATTERENE = {:species => :HATTERENE, :region => Galar, :moves => [:PSYCHIC, :DAZZLINGGLEAM, :CALMMIND, :SHADOWBALL], :form => 0, :ability_index => 1}
	GRIMMSNARL = {:species => :GRIMMSNARL, :region => Galar, :moves => [:PLAYROUGH, :FOULPLAY, :SPIRITBREAK, :FALSESURRENDER], :form => 0, :ability_index => 0}
	OBSTAGOON = {:species => :OBSTAGOON, :region => Galar, :moves => [:FACADE, :KNOCKOFF, :REST, :SLEEPTALK], :form => 0, :ability_index => 1}
	PERRSERKER = {:species => :PERRSERKER, :region => Galar, :moves => [:SWORDSDANCE, :IRONHEAD, :SEEDBOMB, :SUBSTITUTE], :form => 0, :ability_index => 1}
	CURSOLA = {:species => :CURSOLA, :region => Galar, :moves => [:SHADOWBALL, :METEORBEAM, :BURNINGJEALOUSY, :ENDURE], :form => 0, :ability_index => 0}
	SIRFETCHD = {:species => :SIRFETCHD, :region => Galar, :moves => [:CLOSECOMBAT, :KNOCKOFF, :FIRSTIMPRESSION, :POISONJAB], :form => 0, :ability_index => 0}
	MRRIME = {:species => :MRRIME, :region => Galar, :moves => [:RAPIDSPIN, :ICEBEAM, :PSYCHIC, :FOCUSBLAST], :form => 0, :ability_index => 1}
	RUNERIGUS = {:species => :RUNERIGUS, :region => Galar, :moves => [:STEALTHROCK, :EARTHQUAKE, :WILLOWISP, :POLTERGEIST], :form => 0, :ability_index => 0}
	ALCREMIE = {:species => :ALCREMIE, :region => Galar, :moves => [:DAZZLINGGLEAM, :ENERGYBALL, :MYSTICALFIRE, :LIGHTSCREEN], :form => 0, :ability_index => 0}
	FALINKS = {:species => :FALINKS, :region => Galar, :moves => [:SWORDSDANCE, :CLOSECOMBAT, :THROATCHOP, :ZENHEADBUTT], :form => 0, :ability_index => 0}
	PINCURCHIN = {:species => :PINCURCHIN, :region => Galar, :moves => [:DISCHARGE, :SCALD, :TOXICSPIKES, :RECOVER], :form => 0, :ability_index => 0}
	FROSMOTH = {:species => :FROSMOTH, :region => Galar, :moves => [:ICEBEAM, :BUGBUZZ, :STUNSPORE, :TAILWIND], :form => 0, :ability_index => 0}
	STONJOURNER = {:species => :STONJOURNER, :region => Galar, :moves => [:STONEEDGE, :HEATCRASH, :EARTHQUAKE, :ROCKSLIDE], :form => 0, :ability_index => 0}
	EISCUE = {:species => :EISCUE, :region => Galar, :moves => [:BELLYDRUM, :ICICLECRASH, :ZENHEADBUTT, :SUBSTITUTE], :form => 0, :ability_index => 0}
	INDEEDEE = {:species => :INDEEDEE, :region => Galar, :moves => [:EXPANDINGFORCE, :MYSTICALFIRE, :HYPERVOICE, :DAZZLINGGLEAM], :form => 0, :ability_index => 1}
	MORPEKO = {:species => :MORPEKO, :region => Galar, :moves => [:AURAWHEEL, :PARTINGSHOT, :SUPERFANG, :PROTECT], :form => 0, :ability_index => 0}
	COPPERAJAH = {:species => :COPPERAJAH, :region => Galar, :moves => [:HEAVYSLAM, :POWERWHIP, :STONEEDGE, :HEATCRASH], :form => 0, :ability_index => 0}
	DRACOZOLT = {:species => :DRACOZOLT, :region => Galar, :moves => [:BOLTBEAK, :DRACOMETEOR, :SUBSTITUTE, :FIRESPIN], :form => 0, :ability_index => 0}
	ARCTOZOLT = {:species => :ARCTOZOLT, :region => Galar, :moves => [:SUBSTITUTE, :BOLTBEAK, :BLIZZARD, :LOWKICK], :form => 0, :ability_index => 1}
	DRACOVISH = {:species => :DRACOVISH, :region => Galar, :moves => [:FISHIOUSREND, :PSYCHICFANGS, :CRUNCH, :OUTRAGE], :form => 0, :ability_index => 1}
	ARCTOVISH = {:species => :ARCTOVISH, :region => Galar, :moves => [:FISHIOUSREND, :FREEZEDRY, :ICICLECRASH, :PROTECT], :form => 0, :ability_index => 0}
	DURALUDON = {:species => :DURALUDON, :region => Galar, :moves => [:DRACOMETEOR, :FLASHCANNON, :BODYPRESS, :THUNDERBOLT], :form => 0, :ability_index => 0}
	DRAGAPULT = {:species => :DRAGAPULT, :region => Galar, :moves => [:SHADOWBALL, :DRACOMETEOR, :FLAMETHROWER, :HYDROPUMP], :form => 0, :ability_index => 1}
	MEOWSCARADA	= {:species => :MEOWSCARADA, :region => Paldea, :moves => [:TACKLE, :TACKLE, :TACKLE, :TACKLE], :form => 0, :ability_index => 0}
	SKELEDIRGE	= {:species => :SKELEDIRGE, :region => Paldea, :moves => [:TACKLE, :TACKLE, :TACKLE, :TACKLE], :form => 0, :ability_index => 0}
	QUAQUAVAL	= {:species => :QUAQUAVAL, :region => Paldea, :moves => [:TACKLE, :TACKLE, :TACKLE, :TACKLE], :form => 0, :ability_index => 0}
	OINKOLOGNE	= {:species => :OINKOLOGNE, :region => Paldea, :moves => [:TACKLE, :TACKLE, :TACKLE, :TACKLE], :form => 0, :ability_index => 0}
	SPIDOPS	= {:species => :SPIDOPS, :region => Paldea, :moves => [:TACKLE, :TACKLE, :TACKLE, :TACKLE], :form => 0, :ability_index => 0}
	LOKIX	= {:species => :LOKIX, :region => Paldea, :moves => [:TACKLE, :TACKLE, :TACKLE, :TACKLE], :form => 0, :ability_index => 0}
	PAWMOT	= {:species => :PAWMOT, :region => Paldea, :moves => [:TACKLE, :TACKLE, :TACKLE, :TACKLE], :form => 0, :ability_index => 0}
	MAUSHOLD	= {:species => :MAUSHOLD, :region => Paldea, :moves => [:TACKLE, :TACKLE, :TACKLE, :TACKLE], :form => 0, :ability_index => 0}
	DACHSBUN	= {:species => :DACHSBUN, :region => Paldea, :moves => [:TACKLE, :TACKLE, :TACKLE, :TACKLE], :form => 0, :ability_index => 0}
	ARBOLIVA	= {:species => :ARBOLIVA, :region => Paldea, :moves => [:TACKLE, :TACKLE, :TACKLE, :TACKLE], :form => 0, :ability_index => 0}
	SQUAWKABILLY	= {:species => :SQUAWKABILLY, :region => Paldea, :moves => [:TACKLE, :TACKLE, :TACKLE, :TACKLE], :form => 0, :ability_index => 0}
	GARGANACL	= {:species => :GARGANACL, :region => Paldea, :moves => [:TACKLE, :TACKLE, :TACKLE, :TACKLE], :form => 0, :ability_index => 0}
	ARMAROUGE	= {:species => :ARMAROUGE, :region => Paldea, :moves => [:TACKLE, :TACKLE, :TACKLE, :TACKLE], :form => 0, :ability_index => 0}
	CERULEDGE	= {:species => :CERULEDGE, :region => Paldea, :moves => [:TACKLE, :TACKLE, :TACKLE, :TACKLE], :form => 0, :ability_index => 0}
	BELLIBOLT	= {:species => :BELLIBOLT, :region => Paldea, :moves => [:TACKLE, :TACKLE, :TACKLE, :TACKLE], :form => 0, :ability_index => 0}
	KILOWATTREL	= {:species => :KILOWATTREL, :region => Paldea, :moves => [:TACKLE, :TACKLE, :TACKLE, :TACKLE], :form => 0, :ability_index => 0}
	MABOSSTIFF	= {:species => :MABOSSTIFF, :region => Paldea, :moves => [:TACKLE, :TACKLE, :TACKLE, :TACKLE], :form => 0, :ability_index => 0}
	GRAFAIAI	= {:species => :GRAFAIAI, :region => Paldea, :moves => [:TACKLE, :TACKLE, :TACKLE, :TACKLE], :form => 0, :ability_index => 0}
	BRAMBLEGHAST	= {:species => :BRAMBLEGHAST, :region => Paldea, :moves => [:TACKLE, :TACKLE, :TACKLE, :TACKLE], :form => 0, :ability_index => 0}
	TOEDSCRUEL	= {:species => :TOEDSCRUEL, :region => Paldea, :moves => [:TACKLE, :TACKLE, :TACKLE, :TACKLE], :form => 0, :ability_index => 0}
	KLAWF	= {:species => :KLAWF, :region => Paldea, :moves => [:TACKLE, :TACKLE, :TACKLE, :TACKLE], :form => 0, :ability_index => 0}
	SCOVILLAIN	= {:species => :SCOVILLAIN, :region => Paldea, :moves => [:TACKLE, :TACKLE, :TACKLE, :TACKLE], :form => 0, :ability_index => 0}
	RABSCA	= {:species => :RABSCA, :region => Paldea, :moves => [:TACKLE, :TACKLE, :TACKLE, :TACKLE], :form => 0, :ability_index => 0}
	ESPATHRA	= {:species => :ESPATHRA, :region => Paldea, :moves => [:TACKLE, :TACKLE, :TACKLE, :TACKLE], :form => 0, :ability_index => 0}
	TINKATON	= {:species => :TINKATON, :region => Paldea, :moves => [:TACKLE, :TACKLE, :TACKLE, :TACKLE], :form => 0, :ability_index => 0}
	WUGTRIO	= {:species => :WUGTRIO, :region => Paldea, :moves => [:TACKLE, :TACKLE, :TACKLE, :TACKLE], :form => 0, :ability_index => 0}
	BOMBIRDIER	= {:species => :BOMBIRDIER, :region => Paldea, :moves => [:TACKLE, :TACKLE, :TACKLE, :TACKLE], :form => 0, :ability_index => 0}
	PALAFIN	= {:species => :PALAFIN, :region => Paldea, :moves => [:TACKLE, :TACKLE, :TACKLE, :TACKLE], :form => 0, :ability_index => 0}
	REVAVROOM	= {:species => :REVAVROOM, :region => Paldea, :moves => [:TACKLE, :TACKLE, :TACKLE, :TACKLE], :form => 0, :ability_index => 0}
	CYCLIZAR	= {:species => :CYCLIZAR, :region => Paldea, :moves => [:TACKLE, :TACKLE, :TACKLE, :TACKLE], :form => 0, :ability_index => 0}
	ORTHWORM	= {:species => :ORTHWORM, :region => Paldea, :moves => [:TACKLE, :TACKLE, :TACKLE, :TACKLE], :form => 0, :ability_index => 0}
	GLIMMORA	= {:species => :GLIMMORA, :region => Paldea, :moves => [:TACKLE, :TACKLE, :TACKLE, :TACKLE], :form => 0, :ability_index => 0}
	HOUNDSTONE	= {:species => :HOUNDSTONE, :region => Paldea, :moves => [:TACKLE, :TACKLE, :TACKLE, :TACKLE], :form => 0, :ability_index => 0}
	FLAMIGO	= {:species => :FLAMIGO, :region => Paldea, :moves => [:TACKLE, :TACKLE, :TACKLE, :TACKLE], :form => 0, :ability_index => 0}
	CETITAN	= {:species => :CETITAN, :region => Paldea, :moves => [:TACKLE, :TACKLE, :TACKLE, :TACKLE], :form => 0, :ability_index => 0}
	VELUZA	= {:species => :VELUZA, :region => Paldea, :moves => [:TACKLE, :TACKLE, :TACKLE, :TACKLE], :form => 0, :ability_index => 0}
	DONDOZO	= {:species => :DONDOZO, :region => Paldea, :moves => [:TACKLE, :TACKLE, :TACKLE, :TACKLE], :form => 0, :ability_index => 0}
	TATSUGIRI	= {:species => :TATSUGIRI, :region => Paldea, :moves => [:TACKLE, :TACKLE, :TACKLE, :TACKLE], :form => 0, :ability_index => 0}
	ANNIHILAPE	= {:species => :ANNIHILAPE, :region => Paldea, :moves => [:TACKLE, :TACKLE, :TACKLE, :TACKLE], :form => 0, :ability_index => 0}
	CLODSIRE	= {:species => :CLODSIRE, :region => Paldea, :moves => [:TACKLE, :TACKLE, :TACKLE, :TACKLE], :form => 0, :ability_index => 0}
	FARIGIRAF	= {:species => :FARIGIRAF, :region => Paldea, :moves => [:TACKLE, :TACKLE, :TACKLE, :TACKLE], :form => 0, :ability_index => 0}
	DUDUNSPARCE	= {:species => :DUDUNSPARCE, :region => Paldea, :moves => [:TACKLE, :TACKLE, :TACKLE, :TACKLE], :form => 0, :ability_index => 0}
	KINGAMBIT	= {:species => :KINGAMBIT, :region => Paldea, :moves => [:TACKLE, :TACKLE, :TACKLE, :TACKLE], :form => 0, :ability_index => 0}
	BAXCALIBUR	= {:species => :BAXCALIBUR, :region => Paldea, :moves => [:TACKLE, :TACKLE, :TACKLE, :TACKLE], :form => 0, :ability_index => 0}
end