module SummitPokeInfo
	@allspecies = [:VENUSAUR,:CHARIZARD,:BLASTOISE,:BUTTERFREE,:BEEDRILL,:PIDGEOT,:RATICATE,:RATICATE_ALOLA,:FEAROW,:ARBOK,:RAICHU,:RAICHU_ALOLA,:SANDSLASH,:SANDSLASH_ALOLA,:NIDOQUEEN,:NIDOKING,:CLEFABLE,:NINETALES,:NINETALES_ALOLA,:WIGGLYTUFF,:VILEPLUME,:PARASECT,:VENOMOTH,:DUGTRIO,:DUGTRIO_ALOLA,:PERSIAN,:PERSIAN_ALOLA,:GOLDUCK,:PRIMEAPE,:ARCANINE,:POLIWRATH,:ALAKAZAM,:MACHAMP,:VICTREEBEL,:TENTACRUEL,:GOLEM,:GOLEM_ALOLA,:RAPIDASH,:RAPIDASH_GALAR,:SLOWBRO,:SLOWBRO_GALAR,:DODRIO,:DEWGONG,:MUK,:MUK_ALOLA,:CLOYSTER,:GENGAR,:HYPNO,:KINGLER,:ELECTRODE,:EXEGGUTOR,:EXEGGUTOR_ALOLA,:MAROWAK,:MAROWAK_ALOLA,:HITMONLEE,:HITMONCHAN,:WEEZING,:WEEZING_GALAR,:KANGASKHAN,:SEAKING,:STARMIE,:MRMIME,:JYNX,:PINSIR,:TAUROS,:GYARADOS,:LAPRAS,:DITTO,:VAPOREON,:JOLTEON,:FLAREON,:OMASTAR,:KABUTOPS,:AERODACTYL,:SNORLAX,:DRAGONITE,:MEGANIUM,:TYPHLOSION,:FERALIGATR,:FURRET,:NOCTOWL,:LEDIAN,:ARIADOS,:CROBAT,:LANTURN,:XATU,:AMPHAROS,:BELLOSSOM,:AZUMARILL,:SUDOWOODO,:POLITOED,:JUMPLUFF,:SUNFLORA,:QUAGSIRE,:ESPEON,:UMBREON,:SLOWKING,:SLOWKING_GALAR,:WOBBUFFET,:GIRAFARIG,:FORRETRESS,:STEELIX,:GRANBULL,:SCIZOR,:HERACROSS,:MAGCARGO,:URSARING,:OCTILLERY,:MANTINE,:SKARMORY,:HOUNDOOM,:KINGDRA,:DONPHAN,:HITMONTOP,:MILTANK,:BLISSEY,:TYRANITAR,:SCEPTILE,:BLAZIKEN,:SWAMPERT,:MIGHTYENA,:BEAUTIFLY,:DUSTOX,:LUDICOLO,:SHIFTRY,:SWELLOW,:PELIPPER,:GARDEVOIR,:MASQUERAIN,:BRELOOM,:SLAKING,:NINJASK,:SHEDINJA,:EXPLOUD,:HARIYAMA,:DELCATTY,:SABLEYE,:MAWILE,:AGGRON,:MEDICHAM,:MANECTRIC,:SWALOT,:SHARPEDO,:WAILORD,:CAMERUPT,:TORKOAL,:GRUMPIG,:FLYGON,:CACTURNE,:ALTARIA,:ZANGOOSE,:SEVIPER,:LUNATONE,:SOLROCK,:WHISCASH,:CRAWDAUNT,:CLAYDOL,:CRADILY,:ARMALDO,:MILOTIC,:BANETTE,:TROPIUS,:CHIMECHO,:ABSOL,:GLALIE,:WALREIN,:HUNTAIL,:GOREBYSS,:RELICANTH,:SALAMENCE,:METAGROSS,:TORTERRA,:INFERNAPE,:EMPOLEON,:STARAPTOR,:BIBAREL,:KRICKETUNE,:LUXRAY,:ROSERADE,:RAMPARDOS,:BASTIODON,:WORMADAM_PLANTCLOAK,:WORMADAM_SANDYCLOAK,:WORMADAM_TRASHCLOAK,:MOTHIM,:VESPIQUEN,:PACHIRISU,:FLOATZEL,:CHERRIM,:GASTRODON,:AMBIPOM,:DRIFBLIM,:LOPUNNY,:MISMAGIUS,:HONCHKROW,:PURUGLY,:SKUNTANK,:BRONZONG,:SPIRITOMB,:GARCHOMP,:LUCARIO,:HIPPOWDON,:DRAPION,:TOXICROAK,:CARNIVINE,:LUMINEON,:ABOMASNOW,:WEAVILE,:MAGNEZONE,:LICKILICKY,:RHYPERIOR,:TANGROWTH,:ELECTIVIRE,:MAGMORTAR,:TOGEKISS,:YANMEGA,:LEAFEON,:GLACEON,:GLISCOR,:MAMOSWINE,:PORYGONZ,:GALLADE,:PROBOPASS,:DUSKNOIR,:FROSLASS,:ROTOM,:ROTOM_HEAT,:ROTOM_WASH,:ROTOM_FROST,:ROTOM_FAN,:ROTOM_MOW,:SERPERIOR,:EMBOAR,:SAMUROTT,:WATCHOG,:STOUTLAND,:LIEPARD,:SIMISAGE,:SIMISEAR,:SIMIPOUR,:MUSHARNA,:UNFEZANT,:ZEBSTRIKA,:GIGALITH,:SWOOBAT,:EXCADRILL,:AUDINO,:CONKELDURR,:SEISMITOAD,:THROH,:SAWK,:LEAVANNY,:SCOLIPEDE,:WHIMSICOTT,:LILLIGANT,:KROOKODILE,:DARMANITAN,:DARMANITAN_GALAR,:MARACTUS,:CRUSTLE,:SCRAFTY,:SIGILYPH,:COFAGRIGUS,:CARRACOSTA,:ARCHEOPS,:GARBODOR,:ZOROARK,:CINCCINO,:GOTHITELLE,:REUNICLUS,:SWANNA,:VANILLUXE,:SAWSBUCK,:EMOLGA,:ESCAVALIER,:AMOONGUSS,:JELLICENT,:ALOMOMOLA,:GALVANTULA,:FERROTHORN,:KLINKLANG,:EELEKTROSS,:BEHEEYEM,:CHANDELURE,:HAXORUS,:BEARTIC,:CRYOGONAL,:ACCELGOR,:STUNFISK,:STUNFISK_GALAR,:MIENSHAO,:DRUDDIGON,:GOLURK,:BISHARP,:BOUFFALANT,:BRAVIARY,:MANDIBUZZ,:HEATMOR,:DURANT,:HYDREIGON,:VOLCARONA,:CHESNAUGHT,:DELPHOX,:GRENINJA,:DIGGERSBY,:TALONFLAME,:VIVILLON,:PYROAR,:FLORGES,:GOGOAT,:PANGORO,:FURFROU,:MEOWSTIC,:AEGISLASH,:AROMATISSE,:SLURPUFF,:MALAMAR,:BARBARACLE,:DRAGALGE,:CLAWITZER,:HELIOLISK,:TYRANTRUM,:AURORUS,:SYLVEON,:HAWLUCHA,:DEDENNE,:CARBINK,:GOODRA,:KLEFKI,:TREVENANT,:GOURGEIST,:AVALUGG,:NOIVERN,:DECIDUEYE,:INCINEROAR,:PRIMARINA,:TOUCANNON,:GUMSHOOS,:VIKAVOLT,:CRABOMINABLE,:RIBOMBEE,:WISHIWASHI,:LYCANROC_MIDDAY,:LYCANROC_MIDNIGHT,:LYCANROC_DUSK,:TOXAPEX,:MUDSDALE,:ARAQUANID,:LURANTIS,:SHIINOTIC,:SALAZZLE,:BEWEAR,:TSAREENA,:COMFEY,:ORANGURU,:PASSIMIAN,:GOLISOPOD,:PALOSSAND,:PYUKUMUKU,:ORICORIO_BAILE,:ORICORIO_POMPOM,:ORICORIO_PAU,:ORICORIO_SENSU,:MINIOR,:KOMALA,:TURTONATOR,:TOGEDEMARU,:MIMIKYU,:BRUXISH,:DRAMPA,:DHELMISE,:KOMMOO,:RILLABOOM,:CINDERACE,:INTELEON,:GREEDENT,:CORVIKNIGHT,:ORBEETLE,:THIEVUL,:ELDEGOSS,:DUBWOOL,:DREDNAW,:BOLTUND,:COALOSSAL,:FLAPPLE,:APPLETUN,:SANDACONDA,:CRAMORANT,:BARRASKEWDA,:TOXTRICITY,:CENTISKORCH,:GRAPPLOCT,:POLTEAGEIST,:HATTERENE,:GRIMMSNARL,:OBSTAGOON,:PERRSERKER,:CURSOLA,:SIRFETCHD,:MRRIME,:RUNERIGUS,:ALCREMIE,:FALINKS,:PINCURCHIN,:FROSMOTH,:STONJOURNER,:EISCUE,:INDEEDEE,:MORPEKO,:COPPERAJAH,:DRACOZOLT,:ARCTOZOLT,:DRACOVISH,:ARCTOVISH,:DURALUDON,:DRAGAPULT]
	
	def self.allspecies
		return @allspecies
	end

	VENUSAUR = {:species => :VENUSAUR, :moves => [:PETALDANCE, :ENERGYBALL, :SLUDGEBOMB, :TOXIC], :form => 0, :ability_index => 0}
	CHARIZARD = {:species => :CHARIZARD, :moves => [:DRAGONPULSE, :FLAMETHROWER, :AIRSLASH, :OVERHEAT], :form => 0, :ability_index => 0}
	BLASTOISE = {:species => :BLASTOISE, :moves => [:AQUATAIL, :SURF, :FLASHCANNON, :SHELLSMASH], :form => 0, :ability_index => 0}
	BUTTERFREE = {:species => :BUTTERFREE, :moves => [:BUGBUZZ, :PSYCHIC, :POISONPOWDER, :AIRSLASH], :form => 0, :ability_index => 0}
	BEEDRILL = {:species => :BEEDRILL, :moves => [:POISONJAB, :BUGBITE, :ENDEAVOR, :ASSURANCE], :form => 0, :ability_index => 0}
	PIDGEOT = {:species => :PIDGEOT, :moves => [:AIRSLASH, :ROOST, :AERIALACE, :QUICKATTACK], :form => 0, :ability_index => 1}
	RATICATE = {:species => :RATICATE, :moves => [:QUICKATTACK, :CRUNCH, :SWORDSDANCE, :DIG], :form => 0, :ability_index => 1}
	RATICATE_ALOLA = {:species => :RATICATE, :moves => [:CRUNCH, :SUCKERPUNCH, :DOUBLEEDGE, :SCARYFACE], :form => 1, :ability_index => 1}
	FEAROW = {:species => :FEAROW, :moves => [:DRILLRUN, :AERIALACE, :UTURN, :STEELWING], :form => 0, :ability_index => 0}
	ARBOK = {:species => :ARBOK, :moves => [:CRUNCH, :GUNKSHOT, :ICEFANG, :GLARE], :form => 0, :ability_index => 0}
	RAICHU = {:species => :RAICHU, :moves => [:THUNDER, :RAINDANCE, :THUNDERBOLT, :SURF], :form => 0, :ability_index => 0}
	RAICHU_ALOLA = {:species => :RAICHU, :moves => [:PSYCHIC, :THUNDERBOLT, :DRAININGKISS, :SURF], :form => 1, :ability_index => 0}
	SANDSLASH = {:species => :SANDSLASH, :moves => [:EARTHQUAKE, :ROLLOUT, :SWORDSDANCE, :SLASH], :form => 0, :ability_index => 0}
	SANDSLASH_ALOLA = {:species => :SANDSLASH, :moves => [:IRONHEAD, :ICICLECRASH, :ICICLESPEAR, :IRONDEFENSE], :form => 1, :ability_index => 0}
	NIDOQUEEN = {:species => :NIDOQUEEN, :moves => [:TOXICSPIKES, :CRUNCH, :EARTHPOWER, :SUPERPOWER], :form => 0, :ability_index => 0}
	NIDOKING = {:species => :NIDOKING, :moves => [:POISONJAB, :EARTHQUAKE, :MEGAHORN, :TOXIC], :form => 0, :ability_index => 0}
	CLEFABLE = {:species => :CLEFABLE, :moves => [:MOONBLAST, :METRONOME, :PSYCHIC, :FLAMETHROWER], :form => 0, :ability_index => 1}
	NINETALES = {:species => :NINETALES, :moves => [:FLAMETHROWER, :WILLOWISP, :DISABLE, :ENERGYBALL], :form => 0, :ability_index => 0}
	NINETALES_ALOLA = {:species => :NINETALES, :moves => [:DAZZLINGGLEAM, :ICEBEAM, :NASTYPLOT, :SHADOWBALL], :form => 1, :ability_index => 0}
	WIGGLYTUFF = {:species => :WIGGLYTUFF, :moves => [:PLAYROUGH, :PSYCHIC, :THUNDERBOLT, :MIMIC], :form => 0, :ability_index => 1}
	VILEPLUME = {:species => :VILEPLUME, :moves => [:GIGADRAIN, :PETALDANCE, :SLUDGEWAVE, :DAZZLINGGLEAM], :form => 0, :ability_index => 0}
	PARASECT = {:species => :PARASECT, :moves => [:CROSSPOISON, :XSCISSOR, :STUNSPORE, :POISONPOWDER], :form => 0, :ability_index => 0}
	VENOMOTH = {:species => :VENOMOTH, :moves => [:BUGBUZZ, :ENERGYBALL, :SLUDGEBOMB, :PROTECT], :form => 0, :ability_index => 1}
	DUGTRIO = {:species => :DUGTRIO, :moves => [:SANDTOMB, :NIGHTSLASH, :EARTHQUAKE, :SANDSTORM], :form => 0, :ability_index => 0}
	DUGTRIO_ALOLA = {:species => :DUGTRIO, :moves => [:IRONHEAD, :DIG, :EARTHQUAKE, :SUCKERPUNCH], :form => 1, :ability_index => 1}
	PERSIAN = {:species => :PERSIAN, :moves => [:ASSURANCE, :SLASH, :PLAYROUGH, :DIG], :form => 0, :ability_index => 0}
	PERSIAN_ALOLA = {:species => :PERSIAN, :moves => [:POWERGEM, :THUNDERBOLT, :SHADOWBALL, :DARKPULSE], :form => 1, :ability_index => 0}
	GOLDUCK = {:species => :GOLDUCK, :moves => [:HYDROPUMP, :SURF, :PSYCHIC, :CALMMIND], :form => 0, :ability_index => 1}
	PRIMEAPE = {:species => :PRIMEAPE, :moves => [:OUTRAGE, :STOMPINGTANTRUM, :CLOSECOMBAT, :SWAGGER], :form => 0, :ability_index => 0}
	ARCANINE = {:species => :ARCANINE, :moves => [:FLAMETHROWER, :FLAREBLITZ, :EXTREMESPEED, :PLAYROUGH], :form => 0, :ability_index => 0}
	POLIWRATH = {:species => :POLIWRATH, :moves => [:DRAINPUNCH, :DIVE, :EARTHQUAKE, :POISONJAB], :form => 0, :ability_index => 0}
	ALAKAZAM = {:species => :ALAKAZAM, :moves => [:PSYCHIC, :CALMMIND, :DAZZLINGGLEAM, :SHADOWBALL], :form => 0, :ability_index => 0}
	MACHAMP = {:species => :MACHAMP, :moves => [:STONEEDGE, :DARKESTLARIAT, :CLOSECOMBAT, :BRICKBREAK], :form => 0, :ability_index => 0}
	VICTREEBEL = {:species => :VICTREEBEL, :moves => [:LEAFTORNADO, :LEAFBLADE, :POISONJAB, :SLEEPPOWDER], :form => 0, :ability_index => 0}
	TENTACRUEL = {:species => :TENTACRUEL, :moves => [:SLUDGEWAVE, :SURF, :HEX, :SCALD], :form => 0, :ability_index => 1}
	GOLEM = {:species => :GOLEM, :moves => [:EARTHQUAKE, :STONEEDGE, :HEAVYSLAM, :SANDSTORM], :form => 0, :ability_index => 1}
	GOLEM_ALOLA = {:species => :GOLEM, :moves => [:STONEEDGE, :THUNDERPUNCH, :EARTHQUAKE, :GYROBALL], :form => 1, :ability_index => 1}
	RAPIDASH = {:species => :RAPIDASH, :moves => [:SMARTSTRIKE, :FLAMEWHEEL, :FLAREBLITZ, :POISONJAB], :form => 0, :ability_index => 1}
	RAPIDASH_GALAR = {:species => :RAPIDASH, :moves => [:PSYCHOCUT, :DRILLRUN, :MEGAHORN, :PLAYROUGH], :form => 1, :ability_index => 1}
	SLOWBRO = {:species => :SLOWBRO, :moves => [:SURF, :PSYCHIC, :SHADOWBALL, :PROTECT], :form => 0, :ability_index => 1}
	SLOWBRO_GALAR = {:species => :SLOWBRO, :moves => [:SHELLSIDEARM, :SURF, :PSYCHIC, :ZENHEADBUTT], :form => 1, :ability_index => 0}
	DODRIO = {:species => :DODRIO, :moves => [:LUNGE, :DRILLPECK, :FLY, :STEELWING], :form => 0, :ability_index => 1}
	DEWGONG = {:species => :DEWGONG, :moves => [:ICEBEAM, :AQUATAIL, :ICESHARD, :AQUARING], :form => 0, :ability_index => 0}
	MUK = {:species => :MUK, :moves => [:SLUDGEWAVE, :SLUDGEBOMB, :DARKPULSE, :FLAMETHROWER], :form => 0, :ability_index => 0}
	MUK_ALOLA = {:species => :MUK, :moves => [:GUNKSHOT, :KNOCKOFF, :TOXIC, :VENOMDRENCH], :form => 1, :ability_index => 0}
	CLOYSTER = {:species => :CLOYSTER, :moves => [:ICICLESPEAR, :SURF, :ROCKBLAST, :PINMISSILE], :form => 0, :ability_index => 1}
	GENGAR = {:species => :GENGAR, :moves => [:DARKPULSE, :SHADOWBALL, :SLUDGEBOMB, :THUNDERBOLT], :form => 0, :ability_index => 0}
	HYPNO = {:species => :HYPNO, :moves => [:PSYCHIC, :HYPNOSIS, :DREAMEATER, :SHADOWBALL], :form => 0, :ability_index => 1}
	KINGLER = {:species => :KINGLER, :moves => [:CRABHAMMER, :METALCLAW, :STOMPINGTANTRUM, :XSCISSOR], :form => 0, :ability_index => 0}
	ELECTRODE = {:species => :ELECTRODE, :moves => [:DISCHARGE, :THUNDERBOLT, :LIGHTSCREEN, :THUNDERWAVE], :form => 0, :ability_index => 1}
	EXEGGUTOR = {:species => :EXEGGUTOR, :moves => [:PSYSHOCK, :GIGADRAIN, :LEAFSTORM, :SLUDGEBOMB], :form => 0, :ability_index => 0}
	EXEGGUTOR_ALOLA = {:species => :EXEGGUTOR, :moves => [:DRAGONHAMMER, :GIGADRAIN, :LEAFSTORM, :DRAGONPULSE], :form => 1, :ability_index => 0}
	MAROWAK = {:species => :MAROWAK, :moves => [:GIGAIMPACT, :BONEMERANG, :ROCKTOMB, :EARTHQUAKE], :form => 0, :ability_index => 0}
	MAROWAK_ALOLA = {:species => :MAROWAK, :moves => [:SHADOWBONE, :STOMPINGTANTRUM, :FLAREBLITZ, :FLAMEWHEEL], :form => 1, :ability_index => 0}
	HITMONLEE = {:species => :HITMONLEE, :moves => [:BLAZEKICK, :BRICKBREAK, :POISONJAB, :THROATCHOP], :form => 0, :ability_index => 0}
	HITMONCHAN = {:species => :HITMONCHAN, :moves => [:DRAINPUNCH, :POWERUPPUNCH, :THUNDERPUNCH, :BULLETPUNCH], :form => 0, :ability_index => 1}
	WEEZING = {:species => :WEEZING, :moves => [:ASSURANCE, :TOXIC, :SLUDGEBOMB, :HEATWAVE], :form => 0, :ability_index => 0}
	WEEZING_GALAR = {:species => :WEEZING, :moves => [:STRANGESTEAM, :SLUDGEBOMB, :MISTYTERRAIN, :THUNDERBOLT], :form => 1, :ability_index => 1}
	KANGASKHAN = {:species => :KANGASKHAN, :moves => [:OUTRAGE, :BRICKBREAK, :DRAINPUNCH, :BODYSLAM], :form => 0, :ability_index => 1}
	SEAKING = {:species => :SEAKING, :moves => [:WATERFALL, :MEGAHORN, :RAINDANCE, :SMARTSTRIKE], :form => 0, :ability_index => 0}
	STARMIE = {:species => :STARMIE, :moves => [:PSYCHIC, :HYDROPUMP, :POWERGEM, :RECOVER], :form => 0, :ability_index => 1}
	MRMIME = {:species => :MRMIME, :moves => [:PSYCHIC, :DAZZLINGGLEAM, :MAGICALLEAF, :CALMMIND], :form => 0, :ability_index => 1}
	JYNX = {:species => :JYNX, :moves => [:PSYCHIC, :BLIZZARD, :ICEBEAM, :SHADOWBALL], :form => 0, :ability_index => 0}
	PINSIR = {:species => :PINSIR, :moves => [:SUPERPOWER, :XSCISSOR, :SWORDSDANCE, :SUBMISSION], :form => 0, :ability_index => 0}
	TAUROS = {:species => :TAUROS, :moves => [:ASSURANCE, :ZENHEADBUTT, :STOMPINGTANTRUM, :STONEEDGE], :form => 0, :ability_index => 0}
	GYARADOS = {:species => :GYARADOS, :moves => [:ICEFANG, :BOUNCE, :OUTRAGE, :AQUATAIL], :form => 0, :ability_index => 0}
	LAPRAS = {:species => :LAPRAS, :moves => [:ICEBEAM, :BRINE, :RAINDANCE, :SING], :form => 0, :ability_index => 0}
	DITTO = {:species => :DITTO, :moves => [:TRANSFORM, nil, nil, nil], :form => 0, :ability_index => 0}
	VAPOREON = {:species => :VAPOREON, :moves => [:BRINE, :ICEBEAM, :SHADOWBALL, :AQUARING], :form => 0, :ability_index => 0}
	JOLTEON = {:species => :JOLTEON, :moves => [:THUNDERBOLT, :THUNDER, :SHADOWBALL, :RAINDANCE], :form => 0, :ability_index => 0}
	FLAREON = {:species => :FLAREON, :moves => [:FLAREBLITZ, :BITE, :IRONTAIL, :SUPERPOWER], :form => 0, :ability_index => 0}
	OMASTAR = {:species => :OMASTAR, :moves => [:BRINE, :ANCIENTPOWER, :EARTHPOWER, :SCALD], :form => 0, :ability_index => 0}
	KABUTOPS = {:species => :KABUTOPS, :moves => [:AQUAJET, :LIQUIDATION, :LEECHLIFE, :STONEEDGE], :form => 0, :ability_index => 0}
	AERODACTYL = {:species => :AERODACTYL, :moves => [:GIGAIMPACT, :ROCKSLIDE, :STONEEDGE, :IRONHEAD], :form => 0, :ability_index => 0}
	SNORLAX = {:species => :SNORLAX, :moves => [:HAMMERARM, :HIGHHORSEPOWER, :HEAVYSLAM, :BODYSLAM], :form => 0, :ability_index => 0}
	DRAGONITE = {:species => :DRAGONITE, :moves => [:OUTRAGE, :THUNDERPUNCH, :STONEEDGE, :DRAGONDANCE], :form => 0, :ability_index => 0}
	MEGANIUM = {:species => :MEGANIUM, :moves => [:DRAGONTAIL, :SYNTHESIS, :AROMATHERAPY, :GIGADRAIN], :form => 0, :ability_index => 0}
	TYPHLOSION = {:species => :TYPHLOSION, :moves => [:FLAMETHROWER, :ERUPTION, :FOCUSBLAST, :SUNNYDAY], :form => 0, :ability_index => 0}
	FERALIGATR = {:species => :FERALIGATR, :moves => [:DRAGONDANCE, :WATERFALL, :CRUNCH, :ICEPUNCH], :form => 0, :ability_index => 0}
	FURRET = {:species => :FURRET, :moves => [:SLAM, :FACADE, :IRONTAIL, :REST], :form => 0, :ability_index => 1}
	NOCTOWL = {:species => :NOCTOWL, :moves => [:AIRSLASH, :HYPNOSIS, :DREAMEATER, :MOONBLAST], :form => 0, :ability_index => 1}
	LEDIAN = {:species => :LEDIAN, :moves => [:BUGBUZZ, :AIRSLASH, :REFLECT, :LIGHTSCREEN], :form => 0, :ability_index => 1}
	ARIADOS = {:species => :ARIADOS, :moves => [:LEECHLIFE, :POISONJAB, :CROSSPOISON, :SHADOWSNEAK], :form => 0, :ability_index => 0}
	CROBAT = {:species => :CROBAT, :moves => [:LEECHLIFE, :CROSSPOISON, :BRAVEBIRD, :ZENHEADBUTT], :form => 0, :ability_index => 0}
	LANTURN = {:species => :LANTURN, :moves => [:SCALD, :VOLTSWITCH, :TOXIC, :PROTECT], :form => 0, :ability_index => 0}
	XATU = {:species => :XATU, :moves => [:PSYCHIC, :HEATWAVE, :ROOST, :TELEPORT], :form => 0, :ability_index => 0}
	AMPHAROS = {:species => :AMPHAROS, :moves => [:DRAGONPULSE, :POWERGEM, :DISCHARGE, :LIGHTSCREEN], :form => 0, :ability_index => 0}
	BELLOSSOM = {:species => :BELLOSSOM, :moves => [:MOONBLAST, :SOLARBEAM, :GIGADRAIN, :MOONLIGHT], :form => 0, :ability_index => 0}
	AZUMARILL = {:species => :AZUMARILL, :moves => [:AQUATAIL, :PLAYROUGH, :BULLDOZE, :BOUNCE], :form => 0, :ability_index => 1}
	SUDOWOODO = {:species => :SUDOWOODO, :moves => [:STEALTHROCK, :STONEEDGE, :WOODHAMMER, :SUCKERPUNCH], :form => 0, :ability_index => 0}
	POLITOED = {:species => :POLITOED, :moves => [:REST, :TOXIC, :SCALD, :PROTECT], :form => 0, :ability_index => 0}
	JUMPLUFF = {:species => :JUMPLUFF, :moves => [:SWORDSDANCE, :GIGADRAIN, :LEECHSEED, :POISONPOWDER], :form => 0, :ability_index => 1}
	SUNFLORA = {:species => :SUNFLORA, :moves => [:PETALDANCE, :SUNNYDAY, :SOLARBEAM, :SLUDGEBOMB], :form => 0, :ability_index => 0}
	QUAGSIRE = {:species => :QUAGSIRE, :moves => [:EARTHQUAKE, :AQUATAIL, :BRICKBREAK, :ROCKTOMB], :form => 0, :ability_index => 1}
	ESPEON = {:species => :ESPEON, :moves => [:PSYCHIC, :DAZZLINGGLEAM, :SHADOWBALL, :REST], :form => 0, :ability_index => 0}
	UMBREON = {:species => :UMBREON, :moves => [:FOULPLAY, :WISH, :PROTECT, :HEALBELL], :form => 0, :ability_index => 0}
	SLOWKING = {:species => :SLOWKING, :moves => [:SCALD, :PSYCHIC, :SLACKOFF, :TELEPORT], :form => 0, :ability_index => 1}
	SLOWKING_GALAR = {:species => :SLOWKING, :moves => [:PSYCHIC, :SLUDGEBOMB, :FLAMETHROWER, :ICEBEAM], :form => 1, :ability_index => 0}
	WOBBUFFET = {:species => :WOBBUFFET, :moves => [:DESTINYBOND, :COUNTER, :ENCORE, :MIRRORCOAT], :form => 0, :ability_index => 0}
	GIRAFARIG = {:species => :GIRAFARIG, :moves => [:ZENHEADBUTT, :EARTHQUAKE, :CRUNCH, :PROTECT], :form => 0, :ability_index => 0}
	FORRETRESS = {:species => :FORRETRESS, :moves => [:HEAVYSLAM, :GYROBALL, :SPIKES, :TOXICSPIKES], :form => 0, :ability_index => 0}
	STEELIX = {:species => :STEELIX, :moves => [:STEALTHROCK, :EARTHQUAKE, :HEAVYSLAM, :TOXIC], :form => 0, :ability_index => 1}
	GRANBULL = {:species => :GRANBULL, :moves => [:PLAYROUGH, :OUTRAGE, :CRUNCH, :TAUNT], :form => 0, :ability_index => 0}
	SCIZOR = {:species => :SCIZOR, :moves => [:BULLETPUNCH, :IRONHEAD, :XSCISSOR, :SWORDSDANCE], :form => 0, :ability_index => 1}
	HERACROSS = {:species => :HERACROSS, :moves => [:FACADE, :THROATCHOP, :MEGAHORN, :CLOSECOMBAT], :form => 0, :ability_index => 1}
	MAGCARGO = {:species => :MAGCARGO, :moves => [:STEALTHROCK, :TOXIC, :LAVAPLUME, :RECOVER], :form => 0, :ability_index => 1}
	URSARING = {:species => :URSARING, :moves => [:SWORDSDANCE, :FACADE, :CRUNCH, :CLOSECOMBAT], :form => 0, :ability_index => 0}
	OCTILLERY = {:species => :OCTILLERY, :moves => [:SURF, :FIREBLAST, :ICEBEAM, :ENERGYBALL], :form => 0, :ability_index => 1}
	MANTINE = {:species => :MANTINE, :moves => [:SCALD, :ROOST, :AIRSLASH, :ICEBEAM], :form => 0, :ability_index => 1}
	SKARMORY = {:species => :SKARMORY, :moves => [:WHIRLWIND, :ROOST, :BRAVEBIRD, :SPIKES], :form => 0, :ability_index => 1}
	HOUNDOOM = {:species => :HOUNDOOM, :moves => [:FLAMETHROWER, :DARKPULSE, :SHADOWBALL, :TAUNT], :form => 0, :ability_index => 0}
	KINGDRA = {:species => :KINGDRA, :moves => [:HYDROPUMP, :DRACOMETEOR, :SURF, :RAINDANCE], :form => 0, :ability_index => 0}
	DONPHAN = {:species => :DONPHAN, :moves => [:EARTHQUAKE, :RAPIDSPIN, :KNOCKOFF, :STEALTHROCK], :form => 0, :ability_index => 0}
	HITMONTOP = {:species => :HITMONTOP, :moves => [:DIG, :CLOSECOMBAT, :SUCKERPUNCH, :DETECT], :form => 0, :ability_index => 0}
	MILTANK = {:species => :MILTANK, :moves => [:STEALTHROCK, :MILKDRINK, :THUNDERWAVE, :SEISMICTOSS], :form => 0, :ability_index => 0}
	BLISSEY = {:species => :BLISSEY, :moves => [:SEISMICTOSS, :SOFTBOILED, :THUNDERWAVE, :TELEPORT], :form => 0, :ability_index => 0}
	TYRANITAR = {:species => :TYRANITAR, :moves => [:STEALTHROCK, :ROCKBLAST, :EARTHQUAKE, :THUNDERWAVE], :form => 0, :ability_index => 0}
	SCEPTILE = {:species => :SCEPTILE, :moves => [:GIGADRAIN, :ENERGYBALL, :DRAGONPULSE, :FOCUSBLAST], :form => 0, :ability_index => 0}
	BLAZIKEN = {:species => :BLAZIKEN, :moves => [:BLAZEKICK, :CLOSECOMBAT, :AERIALACE, :DETECT], :form => 0, :ability_index => 0}
	SWAMPERT = {:species => :SWAMPERT, :moves => [:HAMMERARM, :EARTHQUAKE, :LIQUIDATION, :ROCKSLIDE], :form => 0, :ability_index => 0}
	MIGHTYENA = {:species => :MIGHTYENA, :moves => [:FIREFANG, :THUNDERFANG, :ICEFANG, :CRUNCH], :form => 0, :ability_index => 0}
	BEAUTIFLY = {:species => :BEAUTIFLY, :moves => [:GIGADRAIN, :PROTECT, :QUIVERDANCE, :BUGBUZZ], :form => 0, :ability_index => 0}
	DUSTOX = {:species => :DUSTOX, :moves => [:TOXIC, :VENOSHOCK, :LEECHLIFE, :PROTECT], :form => 0, :ability_index => 0}
	LUDICOLO = {:species => :LUDICOLO, :moves => [:GIGADRAIN, :HYDROPUMP, :ICEBEAM, :RAINDANCE], :form => 0, :ability_index => 0}
	SHIFTRY = {:species => :SHIFTRY, :moves => [:LEAFBLADE, :FOULPLAY, :LOWSWEEP, :PROTECT], :form => 0, :ability_index => 1}
	SWELLOW = {:species => :SWELLOW, :moves => [:BRAVEBIRD, :AERIALACE, :QUICKATTACK, :UTURN], :form => 0, :ability_index => 0}
	PELIPPER = {:species => :PELIPPER, :moves => [:SCALD, :ROOST, :UTURN, :DEFOG], :form => 0, :ability_index => 1}
	GARDEVOIR = {:species => :GARDEVOIR, :moves => [:MOONBLAST, :PSYCHIC, :MYSTICALFIRE, :HEALINGWISH], :form => 0, :ability_index => 1}
	MASQUERAIN = {:species => :MASQUERAIN, :moves => [:STICKYWEB, :BUGBUZZ, :AIRSLASH, :SCALD], :form => 0, :ability_index => 0}
	BRELOOM = {:species => :BRELOOM, :moves => [:DRAINPUNCH, :SEEDBOMB, :MACHPUNCH, :STONEEDGE], :form => 0, :ability_index => 1}
	SLAKING = {:species => :SLAKING, :moves => [:EARTHQUAKE, :FIREBLAST, :RETALIATE, :SUCKERPUNCH], :form => 0, :ability_index => 0}
	NINJASK = {:species => :NINJASK, :moves => [:XSCISSOR, :METALCLAW, :AERIALACE, :PROTECT], :form => 0, :ability_index => 0}
	SHEDINJA = {:species => :SHEDINJA, :moves => [:SHADOWCLAW, :DIG, :PHANTOMFORCE, :SPITE], :form => 0, :ability_index => 0}
	EXPLOUD = {:species => :EXPLOUD, :moves => [:BOOMBURST, :OVERHEAT, :SURF, :FOCUSBLAST], :form => 0, :ability_index => 0}
	HARIYAMA = {:species => :HARIYAMA, :moves => [:CLOSECOMBAT, :KNOCKOFF, :HEAVYSLAM, :STONEEDGE], :form => 0, :ability_index => 0}
	DELCATTY = {:species => :DELCATTY, :moves => [:PLAYROUGH, :FAKEOUT, :STRENGTH, :FACADE], :form => 0, :ability_index => 0}
	SABLEYE = {:species => :SABLEYE, :moves => [:KNOCKOFF, :RECOVER, :WILLOWISP, :ENCORE], :form => 0, :ability_index => 0}
	MAWILE = {:species => :MAWILE, :moves => [:SWORDSDANCE, :PLAYROUGH, :SUCKERPUNCH, :KNOCKOFF], :form => 0, :ability_index => 1}
	AGGRON = {:species => :AGGRON, :moves => [:STEALTHROCK, :HEADSMASH, :HEAVYSLAM, :PROTECT], :form => 0, :ability_index => 1}
	MEDICHAM = {:species => :MEDICHAM, :moves => [:FAKEOUT, :HIGHJUMPKICK, :ZENHEADBUTT, :BULLETPUNCH], :form => 0, :ability_index => 0}
	MANECTRIC = {:species => :MANECTRIC, :moves => [:THUNDERBOLT, :VOLTSWITCH, :ELECTRICTERRAIN, :FLAMETHROWER], :form => 0, :ability_index => 0}
	SWALOT = {:species => :SWALOT, :moves => [:SLUDGEBOMB, :TOXIC, :SHADOWBALL, :EARTHQUAKE], :form => 0, :ability_index => 1}
	SHARPEDO = {:species => :SHARPEDO, :moves => [:WATERFALL, :CRUNCH, :CLOSECOMBAT, :PROTECT], :form => 0, :ability_index => 0}
	WAILORD = {:species => :WAILORD, :moves => [:SUBSTITUTE, :AQUARING, :PROTECT, :BLOCK], :form => 0, :ability_index => 0}
	CAMERUPT = {:species => :CAMERUPT, :moves => [:FIREBLAST, :EARTHPOWER, :REST, :SLEEPTALK], :form => 0, :ability_index => 1}
	TORKOAL = {:species => :TORKOAL, :moves => [:STEALTHROCK, :LAVAPLUME, :RAPIDSPIN, :TOXIC], :form => 0, :ability_index => 1}
	GRUMPIG = {:species => :GRUMPIG, :moves => [:PSYCHIC, :FOCUSBLAST, :SHADOWBALL, :CALMMIND], :form => 0, :ability_index => 0}
	FLYGON = {:species => :FLYGON, :moves => [:DRAGONDANCE, :EARTHQUAKE, :OUTRAGE, :STONEEDGE], :form => 0, :ability_index => 0}
	CACTURNE = {:species => :CACTURNE, :moves => [:SPIKES, :GIGADRAIN, :DARKPULSE, :SUCKERPUNCH], :form => 0, :ability_index => 0}
	ALTARIA = {:species => :ALTARIA, :moves => [:DEFOG, :ROOST, :HURRICANE, :FLAMETHROWER], :form => 0, :ability_index => 0}
	ZANGOOSE = {:species => :ZANGOOSE, :moves => [:FACADE, :SWORDSDANCE, :CLOSECOMBAT, :XSCISSOR], :form => 0, :ability_index => 0}
	SEVIPER = {:species => :SEVIPER, :moves => [:SLUDGEWAVE, :GIGADRAIN, :FLAMETHROWER, :SUCKERPUNCH], :form => 0, :ability_index => 0}
	LUNATONE = {:species => :LUNATONE, :moves => [:METEORBEAM, :PSYSHOCK, :EARTHPOWER, :ROCKPOLISH], :form => 0, :ability_index => 0}
	SOLROCK = {:species => :SOLROCK, :moves => [:STEALTHROCK, :MORNINGSUN, :WILLOWISP, :ZENHEADBUTT], :form => 0, :ability_index => 0}
	WHISCASH = {:species => :WHISCASH, :moves => [:AQUATAIL, :EARTHQUAKE, :THRASH, :ZENHEADBUTT], :form => 0, :ability_index => 1}
	CRAWDAUNT = {:species => :CRAWDAUNT, :moves => [:SWORDSDANCE, :CRABHAMMER, :KNOCKOFF, :AQUAJET], :form => 0, :ability_index => 0}
	CLAYDOL = {:species => :CLAYDOL, :moves => [:PSYCHIC, :SCORCHINGSANDS, :PROTECT, :TELEPORT], :form => 0, :ability_index => 0}
	CRADILY = {:species => :CRADILY, :moves => [:STEALTHROCK, :RECOVER, :TOXIC, :GIGADRAIN], :form => 0, :ability_index => 0}
	ARMALDO = {:species => :ARMALDO, :moves => [:METALCLAW, :XSCISSOR, :STONEEDGE, :PROTECT], :form => 0, :ability_index => 0}
	MILOTIC = {:species => :MILOTIC, :moves => [:SCALD, :RECOVER, :ICEBEAM, :TOXIC], :form => 0, :ability_index => 0}
	BANETTE = {:species => :BANETTE, :moves => [:DESTINYBOND, :SHADOWCLAW, :GUNKSHOT, :KNOCKOFF], :form => 0, :ability_index => 0}
	TROPIUS = {:species => :TROPIUS, :moves => [:LEECHSEED, :SUBSTITUTE, :AIRSLASH, :PROTECT], :form => 0, :ability_index => 1}
	CHIMECHO = {:species => :CHIMECHO, :moves => [:HEALINGWISH, :RECOVER, :PSYCHIC, :THUNDERWAVE], :form => 0, :ability_index => 0}
	ABSOL = {:species => :ABSOL, :moves => [:SWORDSDANCE, :KNOCKOFF, :SUCKERPUNCH, :PLAYROUGH], :form => 0, :ability_index => 1}
	GLALIE = {:species => :GLALIE, :moves => [:HAIL, :CRUNCH, :BLIZZARD, :ICEBEAM], :form => 0, :ability_index => 1}
	WALREIN = {:species => :WALREIN, :moves => [:SWORDSDANCE, :WATERFALL, :ICICLESPEAR, :EARTHQUAKE], :form => 0, :ability_index => 0}
	HUNTAIL = {:species => :HUNTAIL, :moves => [:SHELLSMASH, :WATERFALL, :SUCKERPUNCH, :ICEBEAM], :form => 0, :ability_index => 0}
	GOREBYSS = {:species => :GOREBYSS, :moves => [:SHELLSMASH, :HYDROPUMP, :ICEBEAM, :SUBSTITUTE], :form => 0, :ability_index => 0}
	RELICANTH = {:species => :RELICANTH, :moves => [:HEADSMASH, :WATERFALL, :EARTHQUAKE, :ZENHEADBUTT], :form => 0, :ability_index => 1}
	SALAMENCE = {:species => :SALAMENCE, :moves => [:DRACOMETEOR, :HURRICANE, :FLAMETHROWER, :ROOST], :form => 0, :ability_index => 0}
	METAGROSS = {:species => :METAGROSS, :moves => [:STEALTHROCK, :METEORMASH, :EARTHQUAKE, :TOXIC], :form => 0, :ability_index => 0}
	TORTERRA = {:species => :TORTERRA, :moves => [:STEALTHROCK, :WOODHAMMER, :EARTHQUAKE, :SYNTHESIS], :form => 0, :ability_index => 0}
	INFERNAPE = {:species => :INFERNAPE, :moves => [:NASTYPLOT, :FIREBLAST, :FOCUSBLAST, :FLAMETHROWER], :form => 0, :ability_index => 0}
	EMPOLEON = {:species => :EMPOLEON, :moves => [:SCALD, :FLASHCANNON, :ICEBEAM, :PROTECT], :form => 0, :ability_index => 0}
	STARAPTOR = {:species => :STARAPTOR, :moves => [:AERIALACE, :CLOSECOMBAT, :STEELWING, :DOUBLETEAM], :form => 0, :ability_index => 0}
	BIBAREL = {:species => :BIBAREL, :moves => [:WATERFALL, :BULLDOZE, :THUNDERWAVE, :YAWN], :form => 0, :ability_index => 1}
	KRICKETUNE = {:species => :KRICKETUNE, :moves => [:XSCISSOR, :NIGHTSLASH, :STICKYWEB, :AERIALACE], :form => 0, :ability_index => 0}
	LUXRAY = {:species => :LUXRAY, :moves => [:WILDCHARGE, :THUNDERFANG, :PSYCHICFANGS, :ROAR], :form => 0, :ability_index => 1}
	ROSERADE = {:species => :ROSERADE, :moves => [:GIGADRAIN, :TOXICSPIKES, :LEECHSEED, :GRASSYTERRAIN], :form => 0, :ability_index => 1}
	RAMPARDOS = {:species => :RAMPARDOS, :moves => [:ZENHEADBUTT, :STONEEDGE, :EARTHQUAKE, :AVALANCHE], :form => 0, :ability_index => 0}
	BASTIODON = {:species => :BASTIODON, :moves => [:IRONHEAD, :HEAVYSLAM, :STONEEDGE, :EARTHQUAKE], :form => 0, :ability_index => 0}
	WORMADAM_PLANTCLOAK = {:species => :WORMADAM, :moves => [:PSYCHIC, :BUGBUZZ, :PROTECT, :ENERGYBALL], :form => 0, :ability_index => 0}
	WORMADAM_SANDYCLOAK = {:species => :WORMADAM, :moves => [:PSYCHIC, :BUGBUZZ, :PROTECT, :EARTHPOWER], :form => 1, :ability_index => 0}
	WORMADAM_TRASHCLOAK = {:species => :WORMADAM, :moves => [:PSYCHIC, :BUGBUZZ, :PROTECT, :IRONHEAD], :form => 2, :ability_index => 0}
	MOTHIM = {:species => :MOTHIM, :moves => [:PSYCHIC, :BUGBUZZ, :PROTECT, :AIRSLASH], :form => 0, :ability_index => 0}
	VESPIQUEN = {:species => :VESPIQUEN, :moves => [:ATTACKORDER, :DEFENDORDER, :POWERGEM, :AIRSLASH], :form => 0, :ability_index => 0}
	PACHIRISU = {:species => :PACHIRISU, :moves => [:SPARK, :THUNDERWAVE, :SUPERFANG, :LASTRESORT], :form => 0, :ability_index => 0}
	FLOATZEL = {:species => :FLOATZEL, :moves => [:ICEFANG, :CRUNCH, :AQUATAIL, :AQUAJET], :form => 0, :ability_index => 0}
	CHERRIM = {:species => :CHERRIM, :moves => [:SUNNYDAY, :SOLARBEAM, :DAZZLINGGLEAM, :POLLENPUFF], :form => 0, :ability_index => 0}
	GASTRODON = {:species => :GASTRODON, :moves => [:MUDDYWATER, :WATERPULSE, :ANCIENTPOWER, :EARTHPOWER], :form => 0, :ability_index => 1}
	AMBIPOM = {:species => :AMBIPOM, :moves => [:FAKEOUT, :RETURN, :LOWKICK, :UTURN], :form => 0, :ability_index => 0}
	DRIFBLIM = {:species => :DRIFBLIM, :moves => [:SHADOWBALL, :CALMMIND, :SUBSTITUTE, :THUNDERBOLT], :form => 0, :ability_index => 1}
	LOPUNNY = {:species => :LOPUNNY, :moves => [:CLOSECOMBAT, :BOUNCE, :PLAYROUGH, :DRAINPUNCH], :form => 0, :ability_index => 0}
	MISMAGIUS = {:species => :MISMAGIUS, :moves => [:NASTYPLOT, :SHADOWBALL, :MYSTICALFIRE, :WILLOWISP], :form => 0, :ability_index => 0}
	HONCHKROW = {:species => :HONCHKROW, :moves => [:NIGHTSLASH, :SUCKERPUNCH, :AERIALACE, :STEELWING], :form => 0, :ability_index => 1}
	PURUGLY = {:species => :PURUGLY, :moves => [:BODYSLAM, :AERIALACE, :PLAYROUGH, :SUBSTITUTE], :form => 0, :ability_index => 0}
	SKUNTANK = {:species => :SKUNTANK, :moves => [:FLAMETHROWER, :THIEF, :SHADOWCLAW, :POISONJAB], :form => 0, :ability_index => 0}
	BRONZONG = {:species => :BRONZONG, :moves => [:STEALTHROCK, :TOXIC, :PSYWAVE, :GYROBALL], :form => 0, :ability_index => 0}
	SPIRITOMB = {:species => :SPIRITOMB, :moves => [:REST, :SLEEPTALK, :CALMMIND, :DARKPULSE], :form => 0, :ability_index => 0}
	GARCHOMP = {:species => :GARCHOMP, :moves => [:SWORDSDANCE, :EARTHQUAKE, :FIREFANG, :SCALESHOT], :form => 0, :ability_index => 0}
	LUCARIO = {:species => :LUCARIO, :moves => [:CLOSECOMBAT, :METEORMASH, :SWORDSDANCE, :EXTREMESPEED], :form => 0, :ability_index => 1}
	HIPPOWDON = {:species => :HIPPOWDON, :moves => [:EARTHQUAKE, :TOXIC, :SLACKOFF, :THUNDERFANG], :form => 0, :ability_index => 0}
	DRAPION = {:species => :DRAPION, :moves => [:SWORDSDANCE, :KNOCKOFF, :POISONJAB, :EARTHQUAKE], :form => 0, :ability_index => 0}
	TOXICROAK = {:species => :TOXICROAK, :moves => [:SWORDSDANCE, :GUNKSHOT, :DRAINPUNCH, :KNOCKOFF], :form => 0, :ability_index => 1}
	CARNIVINE = {:species => :CARNIVINE, :moves => [:POWERWHIP, :SEEDBOMB, :CRUNCH, :PROTECT], :form => 0, :ability_index => 0}
	LUMINEON = {:species => :LUMINEON, :moves => [:DEFOG, :SCALD, :UTURN, :TOXIC], :form => 0, :ability_index => 1}
	ABOMASNOW = {:species => :ABOMASNOW, :moves => [:SWORDSDANCE, :ICESHARD, :WOODHAMMER, :EARTHQUAKE], :form => 0, :ability_index => 0}
	WEAVILE = {:species => :WEAVILE, :moves => [:SWORDSDANCE, :TRIPLEAXEL, :KNOCKOFF, :ICESHARD], :form => 0, :ability_index => 0}
	MAGNEZONE = {:species => :MAGNEZONE, :moves => [:IRONDEFENSE, :BODYPRESS, :THUNDERBOLT, :TELEPORT], :form => 0, :ability_index => 1}
	LICKILICKY = {:species => :LICKILICKY, :moves => [:WISH, :PROTECT, :HEALBELL, :KNOCKOFF], :form => 0, :ability_index => 1}
	RHYPERIOR = {:species => :RHYPERIOR, :moves => [:EARTHQUAKE, :STONEEDGE, :STEALTHROCK, :MEGAHORN], :form => 0, :ability_index => 1}
	TANGROWTH = {:species => :TANGROWTH, :moves => [:POWERWHIP, :KNOCKOFF, :SLUDGEBOMB, :FOCUSBLAST], :form => 0, :ability_index => 1}
	ELECTIVIRE = {:species => :ELECTIVIRE, :moves => [:THUNDERBOLT, :FLAMETHROWER, :FOCUSBLAST, :VOLTSWITCH], :form => 0, :ability_index => 0}
	MAGMORTAR = {:species => :MAGMORTAR, :moves => [:FIREBLAST, :THUNDERBOLT, :FOCUSBLAST, :SCORCHINGSANDS], :form => 0, :ability_index => 0}
	TOGEKISS = {:species => :TOGEKISS, :moves => [:ANCIENTPOWER, :AIRSLASH, :DAZZLINGGLEAM, :AURASPHERE], :form => 0, :ability_index => 1}
	YANMEGA = {:species => :YANMEGA, :moves => [:BUGBUZZ, :AIRSLASH, :UTURN, :GIGADRAIN], :form => 0, :ability_index => 0}
	LEAFEON = {:species => :LEAFEON, :moves => [:SWORDSDANCE, :LEAFBLADE, :KNOCKOFF, :SYNTHESIS], :form => 0, :ability_index => 0}
	GLACEON = {:species => :GLACEON, :moves => [:ICEBEAM, :FREEZEDRY, :SHADOWBALL, :WATERPULSE], :form => 0, :ability_index => 0}
	GLISCOR = {:species => :GLISCOR, :moves => [:EARTHQUAKE, :SWORDSDANCE, :XSCISSOR, :POISONJAB], :form => 0, :ability_index => 0}
	MAMOSWINE = {:species => :MAMOSWINE, :moves => [:ICICLECRASH, :EARTHQUAKE, :ICESHARD, :KNOCKOFF], :form => 0, :ability_index => 0}
	PORYGONZ = {:species => :PORYGONZ, :moves => [:TRIATTACK, :SHADOWBALL, :TRICK, :THUNDERBOLT], :form => 0, :ability_index => 0}
	GALLADE = {:species => :GALLADE, :moves => [:SWORDSDANCE, :CLOSECOMBAT, :ZENHEADBUTT, :KNOCKOFF], :form => 0, :ability_index => 0}
	PROBOPASS = {:species => :PROBOPASS, :moves => [:POWERGEM, :DISCHARGE, :EARTHPOWER, :THUNDERWAVE], :form => 0, :ability_index => 0}
	DUSKNOIR = {:species => :DUSKNOIR, :moves => [:POLTERGEIST, :EARTHQUAKE, :SHADOWSNEAK, :POWERUPPUNCH], :form => 0, :ability_index => 0}
	FROSLASS = {:species => :FROSLASS, :moves => [:HAIL, :SHADOWBALL, :FROSTBREATH, :WILLOWISP], :form => 0, :ability_index => 0}
	ROTOM = {:species => :ROTOM, :moves => [:VOLTSWITCH, :SHADOWBALL, :WILLOWISP, :THUNDERBOLT], :form => 0, :ability_index => 0}
	ROTOM_HEAT = {:species => :ROTOM, :moves => [:OVERHEAT, :VOLTSWITCH, :TOXIC, :PAINSPLIT], :form => 1, :ability_index => 0}
	ROTOM_WASH = {:species => :ROTOM, :moves => [:VOLTSWITCH, :HYDROPUMP, :PAINSPLIT, :WILLOWISP], :form => 2, :ability_index => 0}
	ROTOM_FROST = {:species => :ROTOM, :moves => [:NASTYPLOT, :BLIZZARD, :THUNDERBOLT, :PAINSPLIT], :form => 3, :ability_index => 0}
	ROTOM_FAN = {:species => :ROTOM, :moves => [:NASTYPLOT, :THUNDERBOLT, :AIRSLASH, :PAINSPLIT], :form => 4, :ability_index => 0}
	ROTOM_MOW = {:species => :ROTOM, :moves => [:NASTYPLOT, :LEAFSTORM, :VOLTSWITCH, :PAINSPLIT], :form => 5, :ability_index => 0}
	SERPERIOR = {:species => :SERPERIOR, :moves => [:LEAFSTORM, :SUBSTITUTE, :GLARE, :TOXIC], :form => 0, :ability_index => 0}
	EMBOAR = {:species => :EMBOAR, :moves => [:HAMMERARM, :FLAREBLITZ, :ASSURANCE, :STONEEDGE], :form => 0, :ability_index => 0}
	SAMUROTT = {:species => :SAMUROTT, :moves => [:AQUATAIL, :SWORDSDANCE, :AQUAJET, :DRAGONTAIL], :form => 0, :ability_index => 0}
	WATCHOG = {:species => :WATCHOG, :moves => [:HYPERFANG, :HYPNOSIS, :NASTYPLOT, :BATONPASS], :form => 0, :ability_index => 1}
	STOUTLAND = {:species => :STOUTLAND, :moves => [:PLAYROUGH, :DIG, :IRONHEAD, :CRUNCH], :form => 0, :ability_index => 0}
	LIEPARD = {:species => :LIEPARD, :moves => [:NIGHTSLASH, :SUCKERPUNCH, :PLAYROUGH, :SHADOWCLAW], :form => 0, :ability_index => 1}
	SIMISAGE = {:species => :SIMISAGE, :moves => [:SEEDBOMB, :BRICKBREAK, :ROCKSLIDE, :GUNKSHOT], :form => 0, :ability_index => 0}
	SIMISEAR = {:species => :SIMISEAR, :moves => [:WILLOWISP, :FLAMETHROWER, :ACROBATICS, :SHADOWCLAW], :form => 0, :ability_index => 0}
	SIMIPOUR = {:species => :SIMIPOUR, :moves => [:NASTYPLOT, :SURF, :ICEBEAM, :GRASSKNOT], :form => 0, :ability_index => 0}
	MUSHARNA = {:species => :MUSHARNA, :moves => [:FUTURESIGHT, :MOONBLAST, :MOONLIGHT, :HYPNOSIS], :form => 0, :ability_index => 1}
	UNFEZANT = {:species => :UNFEZANT, :moves => [:SKYATTACK, :GIGAIMPACT, :BRAVEBIRD, :REST], :form => 0, :ability_index => 1}
	ZEBSTRIKA = {:species => :ZEBSTRIKA, :moves => [:THUNDERBOLT, :VOLTSWITCH, :OVERHEAT, :HIDDENPOWER], :form => 0, :ability_index => 1}
	GIGALITH = {:species => :GIGALITH, :moves => [:STEALTHROCK, :STONEEDGE, :EARTHQUAKE, :TOXIC], :form => 0, :ability_index => 1}
	SWOOBAT = {:species => :SWOOBAT, :moves => [:PSYCHIC, :AIRSLASH, :STOREDPOWER, :HEATWAVE], :form => 0, :ability_index => 1}
	EXCADRILL = {:species => :EXCADRILL, :moves => [:EARTHQUAKE, :IRONHEAD, :RAPIDSPIN, :TOXIC], :form => 0, :ability_index => 0}
	AUDINO = {:species => :AUDINO, :moves => [:WISH, :PROTECT, :KNOCKOFF, :ENCORE], :form => 0, :ability_index => 0}
	CONKELDURR = {:species => :CONKELDURR, :moves => [:DRAINPUNCH, :FACADE, :KNOCKOFF, :MACHPUNCH], :form => 0, :ability_index => 0}
	SEISMITOAD = {:species => :SEISMITOAD, :moves => [:DRAINPUNCH, :LIQUIDATION, :ROCKSLIDE, :SUPERSONIC], :form => 0, :ability_index => 1}
	THROH = {:species => :THROH, :moves => [:SUPERPOWER, :EARTHQUAKE, :KNOCKOFF, :POISONJAB], :form => 0, :ability_index => 0}
	SAWK = {:species => :SAWK, :moves => [:CLOSECOMBAT, :KNOCKOFF, :POISONJAB, :EARTHQUAKE], :form => 0, :ability_index => 0}
	LEAVANNY = {:species => :LEAVANNY, :moves => [:STICKYWEB, :LEAFBLADE, :XSCISSOR, :MAGICCOAT], :form => 0, :ability_index => 1}
	SCOLIPEDE = {:species => :SCOLIPEDE, :moves => [:MEGAHORN, :TOXIC, :CROSSPOISON, :XSCISSOR], :form => 0, :ability_index => 1}
	WHIMSICOTT = {:species => :WHIMSICOTT, :moves => [:MOONBLAST, :SUNNYDAY, :SOLARBEAM, :ENERGYBALL], :form => 0, :ability_index => 1}
	LILLIGANT = {:species => :LILLIGANT, :moves => [:ENERGYBALL, :SYNTHESIS, :PETALDANCE, :QUIVERDANCE], :form => 0, :ability_index => 1}
	KROOKODILE = {:species => :KROOKODILE, :moves => [:EARTHQUAKE, :KNOCKOFF, :STEALTHROCK, :TAUNT], :form => 0, :ability_index => 1}
	DARMANITAN = {:species => :DARMANITAN, :moves => [:FLAREBLITZ, :UTURN, :ROCKSLIDE, :EARTHQUAKE], :form => 0, :ability_index => 0}
	DARMANITAN_GALAR = {:species => :DARMANITAN, :moves => [:UTURN, :ICICLECRASH, :FLAREBLITZ, :ROCKSLIDE], :form => 2, :ability_index => 0}
	MARACTUS = {:species => :MARACTUS, :moves => [:SPIKES, :ENDEAVOR, :ENERGYBALL, :SUCKERPUNCH], :form => 0, :ability_index => 1}
	CRUSTLE = {:species => :CRUSTLE, :moves => [:XSCISSOR, :STEALTHROCK, :SHELLSMASH, :ROCKSLIDE], :form => 0, :ability_index => 1}
	SCRAFTY = {:species => :SCRAFTY, :moves => [:DRAGONDANCE, :CLOSECOMBAT, :KNOCKOFF, :IRONHEAD], :form => 0, :ability_index => 1}
	SIGILYPH = {:species => :SIGILYPH, :moves => [:CALMMIND, :AIRSLASH, :ROOST, :PSYCHICH], :form => 0, :ability_index => 0}
	COFAGRIGUS = {:species => :COFAGRIGUS, :moves => [:IRONDEFENSE, :BODYPRESS, :SHADOWBALL, :REST], :form => 0, :ability_index => 0}
	CARRACOSTA = {:species => :CARRACOSTA, :moves => [:SHELLSMASH, :STONEEDGE, :AQUAJET, :LIQUIDATION], :form => 0, :ability_index => 1}
	ARCHEOPS = {:species => :ARCHEOPS, :moves => [:STONEEDGE, :EARTHQUAKE, :DUALWINGBEAT, :ROOST], :form => 0, :ability_index => 0}
	GARBODOR = {:species => :GARBODOR, :moves => [:GUNKSHOT, :SPIKES, :STOMPINGTANTRUM, :PAINSPLIT], :form => 0, :ability_index => 0}
	ZOROARK = {:species => :ZOROARK, :moves => [:DARKPULSE, :FLAMETHROWER, :SLUDGEBOMB, :UTURN], :form => 0, :ability_index => 0}
	CINCCINO = {:species => :CINCCINO, :moves => [:TAILSLAP, :TRIPLEAXEL, :BULLETSEED, :KNOCKOFF], :form => 0, :ability_index => 1}
	GOTHITELLE = {:species => :GOTHITELLE, :moves => [:PSYCHIC, :CHARM, :SHADOWBALL, :THUNDERBOLT], :form => 0, :ability_index => 0}
	REUNICLUS = {:species => :REUNICLUS, :moves => [:CALMMIND, :PSYSHOCK, :FOCUSBLAST, :RECOVER], :form => 0, :ability_index => 0}
	SWANNA = {:species => :SWANNA, :moves => [:AERIALACE, :HURRICANE, :WATERPULSE, :ICEBEAM], :form => 0, :ability_index => 0}
	VANILLUXE = {:species => :VANILLUXE, :moves => [:BLIZZARD, :FREEZEDRY, :ICESHARD, :TAUNT], :form => 0, :ability_index => 1}
	SAWSBUCK = {:species => :SAWSBUCK, :moves => [:MEGAHORN, :HORNLEECH, :JUMPKICK, :LEECHSEED], :form => 0, :ability_index => 0}
	EMOLGA = {:species => :EMOLGA, :moves => [:THUNDERBOLT, :UTURN, :ENCORE, :ROOST], :form => 0, :ability_index => 0}
	ESCAVALIER = {:species => :ESCAVALIER, :moves => [:IRONHEAD, :SWORDSDANCE, :XSCISSOR, :BRUTALSWING], :form => 0, :ability_index => 1}
	AMOONGUSS = {:species => :AMOONGUSS, :moves => [:GIGADRAIN, :SLUDGEBOMB, :FOULPLAY, :SPORE], :form => 0, :ability_index => 0}
	JELLICENT = {:species => :JELLICENT, :moves => [:WATERSPOUT, :SHADOWBALL, :TRICK, :SURF], :form => 0, :ability_index => 0}
	ALOMOMOLA = {:species => :ALOMOMOLA, :moves => [:SCALD, :WISH, :PROTECT, :RAINDANCE], :form => 0, :ability_index => 1}
	GALVANTULA = {:species => :GALVANTULA, :moves => [:BUGBUZZ, :ELECTROBALL, :DISCHARGE, :STICKYWEB], :form => 0, :ability_index => 0}
	FERROTHORN = {:species => :FERROTHORN, :moves => [:SPIKES, :KNOCKOFF, :LEECHSEED, :POWERWHIP], :form => 0, :ability_index => 1}
	KLINKLANG = {:species => :KLINKLANG, :moves => [:SHIFTGEAR, :GEARGRIND, :WILDCHARGE, :SUBSTITUTE], :form => 0, :ability_index => 0}
	EELEKTROSS = {:species => :EELEKTROSS, :moves => [:VOLTSWITCH, :GIGADRAIN, :FLAMETHROWER, :DRAINPUNCH], :form => 0, :ability_index => 0}
	BEHEEYEM = {:species => :BEHEEYEM, :moves => [:PSYCHIC, :THUNDERBOLT, :RECOVER, :NASTYPLOT], :form => 0, :ability_index => 1}
	CHANDELURE = {:species => :CHANDELURE, :moves => [:FIREBLAST, :SHADOWBALL, :TOXIC, :ENERGYBALL], :form => 0, :ability_index => 1}
	HAXORUS = {:species => :HAXORUS, :moves => [:SWORDSDANCE, :OUTRAGE, :EARTHQUAKE, :POISONJAB], :form => 0, :ability_index => 0}
	BEARTIC = {:species => :BEARTIC, :moves => [:HAIL, :SWORDSDANCE, :ICICLECRASH, :SUPERPOWER], :form => 0, :ability_index => 0}
	CRYOGONAL = {:species => :CRYOGONAL, :moves => [:RAPIDSPIN, :RECOVER, :FREEZEDRY, :KNOCKOFF], :form => 0, :ability_index => 0}
	ACCELGOR = {:species => :ACCELGOR, :moves => [:BUGBUZZ, :TOXIC, :WATERSHURIKEN, :GIGADRAIN], :form => 0, :ability_index => 1}
	STUNFISK = {:species => :STUNFISK, :moves => [:STEALTHROCK, :DISCHARGE, :EARTHPOWER, :REST], :form => 0, :ability_index => 1}
	STUNFISK_GALAR = {:species => :STUNFISK, :moves => [:STEALTHROCK, :EARTHQUAKE, :YAWN, :METALCLAW], :form => 1, :ability_index => 0}
	MIENSHAO = {:species => :MIENSHAO, :moves => [:HIGHJUMPKICK, :KNOCKOFF, :UTURN, :FAKEOUT], :form => 0, :ability_index => 1}
	DRUDDIGON = {:species => :DRUDDIGON, :moves => [:DRAGONTAIL, :EARTHQUAKE, :GLARE, :TAUNT], :form => 0, :ability_index => 1}
	GOLURK = {:species => :GOLURK, :moves => [:STEALTHROCK, :EARTHQUAKE, :SHADOWPUNCH, :ICEPUNCH], :form => 0, :ability_index => 0}
	BISHARP = {:species => :BISHARP, :moves => [:IRONHEAD, :KNOCKOFF, :SUCKERPUNCH, :SWORDSDANCE], :form => 0, :ability_index => 0}
	BOUFFALANT = {:species => :BOUFFALANT, :moves => [:SUBSTITUTE, :SWORDSDANCE, :BODYSLAM, :THROATCHOP], :form => 0, :ability_index => 1}
	BRAVIARY = {:species => :BRAVIARY, :moves => [:SUBSTITUTE, :BULKUP, :BRAVEBIRD, :ROOST], :form => 0, :ability_index => 0}
	MANDIBUZZ = {:species => :MANDIBUZZ, :moves => [:FOULPLAY, :DEFOG, :UTURN, :ROOST], :form => 0, :ability_index => 1}
	HEATMOR = {:species => :HEATMOR, :moves => [:FIREBLAST, :GIGADRAIN, :FOCUSBLAST, :SCORCHINGSANDS], :form => 0, :ability_index => 0}
	DURANT = {:species => :DURANT, :moves => [:FIRSTIMPRESSION, :SUPERPOWER, :ROCKSLIDE, :IRONHEAD], :form => 0, :ability_index => 0}
	HYDREIGON = {:species => :HYDREIGON, :moves => [:DRACOMETEOR, :DARKPULSE, :FLAMETHROWER, :ROOST], :form => 0, :ability_index => 1}
	VOLCARONA = {:species => :VOLCARONA, :moves => [:QUIVERDANCE, :FLAMETHROWER, :BUGBUZZ, :PSYCHIC], :form => 0, :ability_index => 0}
	CHESNAUGHT = {:species => :CHESNAUGHT, :moves => [:WOODHAMMER, :DRAINPUNCH, :SYNTHESIS, :SPIKEYSHIELD], :form => 0, :ability_index => 0}
	DELPHOX = {:species => :DELPHOX, :moves => [:CALMMIND, :FIREBLAST, :PSYCHIC, :GRASSKNOT], :form => 0, :ability_index => 0}
	GRENINJA = {:species => :GRENINJA, :moves => [:HYDROPUMP, :DARKPULSE, :WATERSHURIKEN, :SPIKES], :form => 0, :ability_index => 0}
	DIGGERSBY = {:species => :DIGGERSBY, :moves => [:EARTHQUAKE, :HAMMERARM, :SWORDSDANCE, :BOUNCE], :form => 0, :ability_index => 0}
	TALONFLAME = {:species => :TALONFLAME, :moves => [:AERIALACE, :FLAMECHARGE, :ACROBATICS, :FLAREBLITZ], :form => 0, :ability_index => 0}
	VIVILLON = {:species => :VIVILLON, :moves => [:DRAININGKISS, :LIGHTSCREEN, :SUPERSONIC, :BUGBUZZ], :form => 0, :ability_index => 0}
	PYROAR = {:species => :PYROAR, :moves => [:FLAMETHROWER, :HYPERVOICE, :DARKPULSE, :WILLOWISP], :form => 0, :ability_index => 0}
	FLORGES = {:species => :FLORGES, :moves => [:MISTYTERRAIN, :MOONBLAST, :GRASSKNOT, :HIDDENPOWER], :form => 0, :ability_index => 0}
	GOGOAT = {:species => :GOGOAT, :moves => [:BULKUP, :HORNLEECH, :EARTHQUAKE, :ROCKSLIDE], :form => 0, :ability_index => 0}
	PANGORO = {:species => :PANGORO, :moves => [:KNOCKOFF, :CLOSECOMBAT, :IRONHEAD, :DRAINPUNCH], :form => 0, :ability_index => 0}
	FURFROU = {:species => :FURFROU, :moves => [:UTURN, :THUNDERWAVE, :SUCKERPUNCH, :CHARM], :form => 0, :ability_index => 0}
	MEOWSTIC = {:species => :MEOWSTIC, :moves => [:REFLECT, :LIGHTSCREEN, :THUNDERWAVE, :PSYCHIC], :form => 0, :ability_index => 0}
	AEGISLASH = {:species => :AEGISLASH, :moves => [:SHADOWBALL, :FLASHCANNON, :CLOSECOMBAT, :KINGSSHIELD], :form => 0, :ability_index => 0}
	AROMATISSE = {:species => :AROMATISSE, :moves => [:MOONBLAST, :WISH, :PROTECT, :HEALBELL], :form => 0, :ability_index => 0}
	SLURPUFF = {:species => :SLURPUFF, :moves => [:STICKYWEB, :MAGICCOAT, :DAZZLINGGLEAM, :YAWN], :form => 0, :ability_index => 0}
	MALAMAR = {:species => :MALAMAR, :moves => [:SUPERPOWER, :KNOCKOFF, :REST, :SLEEPTALK], :form => 0, :ability_index => 0}
	BARBARACLE = {:species => :BARBARACLE, :moves => [:SHELLSMASH, :LIQUIDATION, :STONEEDGE, :GRASSKNOT], :form => 0, :ability_index => 0}
	DRAGALGE = {:species => :DRAGALGE, :moves => [:DRACOMETEOR, :SLUDGEBOMB, :FLIPTURN, :SCALD], :form => 0, :ability_index => 0}
	CLAWITZER = {:species => :CLAWITZER, :moves => [:WATERPULSE, :ICEBEAM, :DARKPULSE, :AURASPHERE], :form => 0, :ability_index => 0}
	HELIOLISK = {:species => :HELIOLISK, :moves => [:THUNDERBOLT, :HYPERVOICE, :VOLTSWITCH, :DARKPULSE], :form => 0, :ability_index => 0}
	TYRANTRUM = {:species => :TYRANTRUM, :moves => [:HEADSMASH, :OUTRAGE, :CLOSECOMBAT, :DRAGONCLAW], :form => 0, :ability_index => 0}
	AURORUS = {:species => :AURORUS, :moves => [:ICEBEAM, :ANCIENTPOWER, :EARTHPOWER, :BLIZZARD], :form => 0, :ability_index => 0}
	SYLVEON = {:species => :SYLVEON, :moves => [:MOONBLAST, :PSYSHOCK, :MISTYTERRAIN, :MYSTICALFIRE], :form => 0, :ability_index => 0}
	HAWLUCHA = {:species => :HAWLUCHA, :moves => [:FLYINGPRESS, :SUBMISSION, :ROCKTOMB, :POISONJAB], :form => 0, :ability_index => 1}
	DEDENNE = {:species => :DEDENNE, :moves => [:THUNDER, :PARABOLICCHARGE, :DAZZLINGGLEAM, :ELECTROWEB], :form => 0, :ability_index => 0}
	CARBINK = {:species => :CARBINK, :moves => [:STEALTHROCK, :MOONBLAST, :PROTECT, :BODYPRESS], :form => 0, :ability_index => 0}
	GOODRA = {:species => :GOODRA, :moves => [:DRACOMETEOR, :THUNDERBOLT, :FIREBLAST, :EARTHQUAKE], :form => 0, :ability_index => 0}
	KLEFKI = {:species => :KLEFKI, :moves => [:SPIKES, :DAZZLINGGLEAM, :THUNDERWAVE, :TOXIC], :form => 0, :ability_index => 0}
	TREVENANT = {:species => :TREVENANT, :moves => [:POLTERGEIST, :WOODHAMMER, :HORNLEECH, :EARTHQUAKE], :form => 0, :ability_index => 0}
	GOURGEIST = {:species => :GOURGEIST, :moves => [:POWERWHIP, :POLTERGEIST, :SHADOWSNEAK, :FIREBLAST], :form => 0, :ability_index => 1}
	AVALUGG = {:species => :AVALUGG, :moves => [:AVALANCHE, :HAIL, :EARTHQUAKE, :STONEEDGE], :form => 0, :ability_index => 1}
	NOIVERN = {:species => :NOIVERN, :moves => [:DRACOMETEOR, :FLAMETHROWER, :ROOST, :UTURN], :form => 0, :ability_index => 1}
	DECIDUEYE = {:species => :DECIDUEYE, :moves => [:POLTERGEIST, :LEAFBLADE, :UTURN, :SHADOWSNEAK], :form => 0, :ability_index => 0}
	INCINEROAR = {:species => :INCINEROAR, :moves => [:DARKESTLARIAT, :OVERHEAT, :SWORDSDANCE, :BRICKBREAK], :form => 0, :ability_index => 0}
	PRIMARINA = {:species => :PRIMARINA, :moves => [:SPARKLINGARIA, :MOONBLAST, :MISTYTERRAIN, :REFLECT], :form => 0, :ability_index => 0}
	TOUCANNON = {:species => :TOUCANNON, :moves => [:BEAKBLAST, :ROCKBLAST, :BULLETSEED, :PLUCK], :form => 0, :ability_index => 1}
	GUMSHOOS = {:species => :GUMSHOOS, :moves => [:HYPERFANG, :CRUNCH, :BULLDOZE, :SUBSTITUTE], :form => 0, :ability_index => 1}
	VIKAVOLT = {:species => :VIKAVOLT, :moves => [:ZAPCANNON, :THUNDERBOLT, :BUGBUZZ, :FLASHCANNON], :form => 0, :ability_index => 0}
	CRABOMINABLE = {:species => :CRABOMINABLE, :moves => [:DRAINPUNCH, :ICEHAMMER, :EARTHQUAKE, :THUNDERPUNCH], :form => 0, :ability_index => 1}
	RIBOMBEE = {:species => :RIBOMBEE, :moves => [:POLLENPUFF, :MOONBLAST, :QUIVERDANCE, :STICKYWEB], :form => 0, :ability_index => 1}
	WISHIWASHI = {:species => :WISHIWASHI, :moves => [:LIQUIDATION, :EARTHQUAKE, :ICEBEAM, :ENDURE], :form => 0, :ability_index => 0}
	LYCANROC_MIDDAY = {:species => :LYCANROC, :moves => [:ACCELEROCK, :STONEEDGE, :CRUNCH, :THUNDERFANG], :form => 0, :ability_index => 0}
	LYCANROC_MIDNIGHT = {:species => :LYCANROC, :moves => [:SWORDSDANCE, :STONEEDGE, :CLOSECOMBAT, :SUCKERPUNCH], :form => 1, :ability_index => 0}
	LYCANROC_DUSK = {:species => :LYCANROC, :moves => [:STONEEDGE, :STEALTHROCK, :ROCKSLIDE, :CRUNCH], :form => 2, :ability_index => 0}
	TOXAPEX = {:species => :TOXAPEX, :moves => [:TOXIC, :TOXICSPIKES, :RECOVER, :SCALD], :form => 0, :ability_index => 0}
	MUDSDALE = {:species => :MUDSDALE, :moves => [:STEALTHROCK, :EARTHQUAKE, :BODYPRESS, :SMACKDOWN], :form => 0, :ability_index => 1}
	ARAQUANID = {:species => :ARAQUANID, :moves => [:LEECHLIFE, :LIQUIDATION, :CRUNCH, :RAINDANCE], :form => 0, :ability_index => 0}
	LURANTIS = {:species => :LURANTIS, :moves => [:LEAFSTORM, :SUPERPOWER, :SYNTHESIS, :SUNNYDAY], :form => 0, :ability_index => 0}
	SHIINOTIC = {:species => :SHIINOTIC, :moves => [:SPORE, :STRENGTHSAP, :GIGADRAIN, :MOONBLAST], :form => 0, :ability_index => 1}
	SALAZZLE = {:species => :SALAZZLE, :moves => [:TOXIC, :SLUDGEWAVE, :FLAMETHROWER, :DRAGONPULSE], :form => 0, :ability_index => 0}
	BEWEAR = {:species => :BEWEAR, :moves => [:SWORDSDANCE, :DOUBLEEDGE, :DRAINPUNCH, :DARKESTLARIAT], :form => 0, :ability_index => 0}
	TSAREENA = {:species => :TSAREENA, :moves => [:TROPKICK, :POWERWHIP, :HIGHJUMPKICK, :UTURN], :form => 0, :ability_index => 1}
	COMFEY = {:species => :COMFEY, :moves => [:SYNTHESIS, :DAZZLINGGLEAM, :LEECHSEED, :CALMMIND], :form => 0, :ability_index => 1}
	ORANGURU = {:species => :ORANGURU, :moves => [:PSYCHIC, :THUNDERBOLT, :NASTYPLOT, :TRICKROOM], :form => 0, :ability_index => 0}
	PASSIMIAN = {:species => :PASSIMIAN, :moves => [:CLOSECOMBAT, :KNOCKOFF, :GUNKSHOT, :ROCKSLIDE], :form => 0, :ability_index => 0}
	GOLISOPOD = {:species => :GOLISOPOD, :moves => [:LIQUIDATION, :FIRSTIMPRESSION, :SUCKERPUNCH, :XSCISSOR], :form => 0, :ability_index => 0}
	PALOSSAND = {:species => :PALOSSAND, :moves => [:EARTHPOWER, :SHADOWBALL, :SHOREUP, :STEALTHROCK], :form => 0, :ability_index => 0}
	PYUKUMUKU = {:species => :PYUKUMUKU, :moves => [:COUNTER, :TOXIC, :PROTECT, :SOAK], :form => 0, :ability_index => 0}
	ORICORIO_BAILE = {:species => :ORICORIO, :moves => [:CALMMIND, :HURRICANE, :REVELATIONDANCE, :ROOST], :form => 0, :ability_index => 0}
	ORICORIO_POMPOM = {:species => :ORICORIO, :moves => [:CALMMIND, :HURRICANE, :REVELATIONDANCE, :ROOST], :form => 1, :ability_index => 0}
	ORICORIO_PAU = {:species => :ORICORIO, :moves => [:CALMMIND, :HURRICANE, :REVELATIONDANCE, :ROOST], :form => 2, :ability_index => 0}
	ORICORIO_SENSU = {:species => :ORICORIO, :moves => [:CALMMIND, :HURRICANE, :REVELATIONDANCE, :ROOST], :form => 3, :ability_index => 0}
	MINIOR = {:species => :MINIOR, :moves => [:SHELLSMASH, :STONEEDGE, :EARTHQUAKE, :ACROBATICS], :form => 0, :ability_index => 0}
	KOMALA = {:species => :KOMALA, :moves => [:WOODHAMMER, :THRASH, :ROLLOUT, :RAPIDSPIN], :form => 0, :ability_index => 0}
	TURTONATOR = {:species => :TURTONATOR, :moves => [:SHELLSMASH, :FIREBLAST, :DRACOMETEOR, :DRAGONPULSE], :form => 0, :ability_index => 0}
	TOGEDEMARU = {:species => :TOGEDEMARU, :moves => [:ZINGZAP, :IRONHEAD, :NUZZLE, :UTURN], :form => 0, :ability_index => 1}
	MIMIKYU = {:species => :MIMIKYU, :moves => [:SWORDSDANCE, :PLAYROUGH, :SHADOWSNEAK, :SHADOWCLAW], :form => 0, :ability_index => 0}
	BRUXISH = {:species => :BRUXISH, :moves => [:SWORDSDANCE, :PSYCHICFANGS, :AQUAJET, :CRUNCH], :form => 0, :ability_index => 1}
	DRAMPA = {:species => :DRAMPA, :moves => [:HYPERVOICE, :DRACOMETEOR, :FLAMETHROWER, :ENERGYBALL], :form => 0, :ability_index => 1}
	DHELMISE = {:species => :DHELMISE, :moves => [:ANCHORSHOT, :POWERWHIP, :POLTERGEIST, :SYNTHESIS], :form => 0, :ability_index => 0}
	KOMMOO = {:species => :KOMMOO, :moves => [:BODYPRESS, :EARTHQUAKE, :FLAMETHROWER, :CLANGINGSCALES], :form => 0, :ability_index => 0}
	RILLABOOM = {:species => :RILLABOOM, :moves => [:SWORDSDANCE, :DRUMBEATING, :EARTHQUAKE, :SUPERPOWER], :form => 0, :ability_index => 0}
	CINDERACE = {:species => :CINDERACE, :moves => [:PYROBALL, :COURTCHANGE, :ZENHEADBUTT, :GUNKSHOT], :form => 0, :ability_index => 0}
	INTELEON = {:species => :INTELEON, :moves => [:SNIPESHOT, :ICEBEAM, :AIRSLASH, :AQUARING], :form => 0, :ability_index => 0}
	GREEDENT = {:species => :GREEDENT, :moves => [:STUFFCHEEKS, :STOCKPILE, :SPITUP, :BELCH], :form => 0, :ability_index => 0}
	CORVIKNIGHT = {:species => :CORVIKNIGHT, :moves => [:IRONHEAD, :DRILLPECK, :PROTECT, :BODYPRESS], :form => 0, :ability_index => 0}
	ORBEETLE = {:species => :ORBEETLE, :moves => [:PSYCHIC, :BUGBUZZ, :REFLECT, :LIGHTSCREEN], :form => 0, :ability_index => 0}
	THIEVUL = {:species => :THIEVUL, :moves => [:NIGHTSLASH, :FOULPLAY, :PLAYROUGH, :DIG], :form => 0, :ability_index => 1}
	ELDEGOSS = {:species => :ELDEGOSS, :moves => [:LEAFSTORM, :LEAFTORNADO, :POLLENPUFF, :SING], :form => 0, :ability_index => 0}
	DUBWOOL = {:species => :DUBWOOL, :moves => [:COTTONGUARD, :BODYPRESS, :REST, :PAYBACK], :form => 0, :ability_index => 0}
	DREDNAW = {:species => :DREDNAW, :moves => [:LIQUIDATION, :ROCKTOMB, :JAWLOCK, :CRUNCH], :form => 0, :ability_index => 0}
	BOLTUND = {:species => :BOLTUND, :moves => [:THUNDERFANG, :FIREFANG, :PLAYROUGH, :PSYCHICFANGS], :form => 0, :ability_index => 0}
	COALOSSAL = {:species => :COALOSSAL, :moves => [:ANCIENTPOWER, :HEATCRASH, :BURNUP, :ROCKBLAST], :form => 0, :ability_index => 0}
	FLAPPLE = {:species => :FLAPPLE, :moves => [:GRAVAPPLE, :OUTRAGE, :GRASSYGLIDE, :SUCKERPUNCH], :form => 0, :ability_index => 0}
	APPLETUN = {:species => :APPLETUN, :moves => [:DRACOMETEOR, :APPLEACID, :DRAGONPULSE, :GIGADRAIN], :form => 0, :ability_index => 0}
	SANDACONDA = {:species => :SANDACONDA, :moves => [:STEALTHROCK, :EARTHQUAKE, :GLARE, :REST], :form => 0, :ability_index => 1}
	CRAMORANT = {:species => :CRAMORANT, :moves => [:ROOST, :SURF, :HURRICANE, :SUBSTITUTE], :form => 0, :ability_index => 0}
	BARRASKEWDA = {:species => :BARRASKEWDA, :moves => [:LIQUIDATION, :CLOSECOMBAT, :FLIPTURN, :PSYCHICFANGS], :form => 0, :ability_index => 0}
	TOXTRICITY = {:species => :TOXTRICITY, :moves => [:BOOMBURST, :OVERDRIVE, :SNARL, :SLUDGEWAVE], :form => 0, :ability_index => 0}
	CENTISKORCH = {:species => :CENTISKORCH, :moves => [:FIRELASH, :LUNGE, :CRUNCH, :POWERWHIP], :form => 0, :ability_index => 1}
	GRAPPLOCT = {:species => :GRAPPLOCT, :moves => [:BULKUP, :DRAINPUNCH, :BRUTALSWING, :SUCKERPUNCH], :form => 0, :ability_index => 0}
	POLTEAGEIST = {:species => :POLTEAGEIST, :moves => [:SHELLSMASH, :SHADOWBALL, :GIGADRAIN, :POLTERGEIST], :form => 0, :ability_index => 0}
	HATTERENE = {:species => :HATTERENE, :moves => [:PSYCHIC, :DAZZLINGGLEAM, :CALMMIND, :SHADOWBALL], :form => 0, :ability_index => 1}
	GRIMMSNARL = {:species => :GRIMMSNARL, :moves => [:PLAYROUGH, :FOULPLAY, :SPIRITBREAK, :FALSESURRENDER], :form => 0, :ability_index => 0}
	OBSTAGOON = {:species => :OBSTAGOON, :moves => [:FACADE, :KNOCKOFF, :REST, :SLEEPTALK], :form => 0, :ability_index => 1}
	PERRSERKER = {:species => :PERRSERKER, :moves => [:SWORDSDANCE, :IRONHEAD, :SEEDBOMB, :SUBSTITUTE], :form => 0, :ability_index => 1}
	CURSOLA = {:species => :CURSOLA, :moves => [:SHADOWBALL, :METEORBEAM, :BURNINGJEALOUSY, :ENDURE], :form => 0, :ability_index => 0}
	SIRFETCHD = {:species => :SIRFETCHD, :moves => [:CLOSECOMBAT, :KNOCKOFF, :FIRSTIMPRESSION, :POISONJAB], :form => 0, :ability_index => 0}
	MRRIME = {:species => :MRRIME, :moves => [:RAPIDSPIN, :ICEBEAM, :PSYCHIC, :FOCUSBLAST], :form => 0, :ability_index => 1}
	RUNERIGUS = {:species => :RUNERIGUS, :moves => [:STEALTHROCK, :EARTHQUAKE, :WILLOWISP, :POLTERGEIST], :form => 0, :ability_index => 0}
	ALCREMIE = {:species => :ALCREMIE, :moves => [:DAZZLINGGLEAM, :ENERGYBALL, :MYSTICALFIRE, :LIGHTSCREEN], :form => 0, :ability_index => 0}
	FALINKS = {:species => :FALINKS, :moves => [:SWORDSDANCE, :CLOSECOMBAT, :THROATCHOP, :ZENHEADBUTT], :form => 0, :ability_index => 0}
	PINCURCHIN = {:species => :PINCURCHIN, :moves => [:DISCHARGE, :SCALD, :TOXICSPIKES, :RECOVER], :form => 0, :ability_index => 0}
	FROSMOTH = {:species => :FROSMOTH, :moves => [:ICEBEAM, :BUGBUZZ, :STUNSPORE, :TAILWIND], :form => 0, :ability_index => 0}
	STONJOURNER = {:species => :STONJOURNER, :moves => [:STONEEDGE, :HEATCRASH, :EARTHQUAKE, :ROCKSLIDE], :form => 0, :ability_index => 0}
	EISCUE = {:species => :EISCUE, :moves => [:BELLYDRUM, :ICICLECRASH, :ZENHEADBUTT, :SUBSTITUTE], :form => 0, :ability_index => 0}
	INDEEDEE = {:species => :INDEEDEE, :moves => [:EXPANDINGFORCE, :MYSTICALFIRE, :HYPERVOICE, :DAZZLINGGLEAM], :form => 0, :ability_index => 1}
	MORPEKO = {:species => :MORPEKO, :moves => [:AURAWHEEL, :PARTINGSHOT, :SUPERFANG, :PROTECT], :form => 0, :ability_index => 0}
	COPPERAJAH = {:species => :COPPERAJAH, :moves => [:HEAVYSLAM, :POWERWHIP, :STONEEDGE, :HEATCRASH], :form => 0, :ability_index => 0}
	DRACOZOLT = {:species => :DRACOZOLT, :moves => [:BOLTBEAK, :DRACOMETEOR, :SUBSTITUTE, :FIRESPIN], :form => 0, :ability_index => 0}
	ARCTOZOLT = {:species => :ARCTOZOLT, :moves => [:SUBSTITUTE, :BOLTBEAK, :BLIZZARD, :LOWKICK], :form => 0, :ability_index => 1}
	DRACOVISH = {:species => :DRACOVISH, :moves => [:FISHIOUSREND, :PSYCHICFANGS, :CRUNCH, :OUTRAGE], :form => 0, :ability_index => 1}
	ARCTOVISH = {:species => :ARCTOVISH, :moves => [:FISHIOUSREND, :FREEZEDRY, :ICICLECRASH, :PROTECT], :form => 0, :ability_index => 0}
	DURALUDON = {:species => :DURALUDON, :moves => [:DRACOMETEOR, :FLASHCANNON, :BODYPRESS, :THUNDERBOLT], :form => 0, :ability_index => 0}
	DRAGAPULT = {:species => :DRAGAPULT, :moves => [:SHADOWBALL, :DRACOMETEOR, :FLAMETHROWER, :HYDROPUMP], :form => 0, :ability_index => 1}
end